### ISSUE TITLE
How to run inference with an existing model?

### ISSUE THREAD

**Issue by xkyi** [haotian-liu/yolact_edge#10]
Thanks for sharing this amazing work,  however when I predict my own image by using `python3 eval.py --config yolact_edge_pytorch_config --trained_model=weights/yolact_edge_14_3000.pth  --top_k=100  --dataset=my_custom_dataset --image=1.jpg:out.jpg`, an error occurred,

```Traceback (most recent call last):
  File "eval.py", line 1393, in <module>
    evaluate(net, dataset)
  File "eval.py", line 870, in evaluate
    evalimage(net, inp, out)
  File "eval.py", line 585, in evalimage
    img_numpy = prep_display(preds, frame, None, None, undo_transform=False)
  File "eval.py", line 232, in prep_display
    _class = cfg.dataset.class_names[classes[j]]
IndexError: tuple index out of range
```
Besides, when I use `python3 eval.py --coco_transfer --config yolact_edge_pytorch_config --trained_model=weights/yolact_edge_54_800000.pth --score_threshold=0.3 --top_k=100 --image=test.jpg:out.jpg`  to predict a coco image, it works.

**Comment by haotian-liu** [comment]
It seems that the predicted class id is out of range. Please check `class_names` of your custom dataset as well as `cfg.num_classes`.

For instance, when `cfg.num_classes` is set to 81 (which is COCO's setting), and you only set your `class_names` with a tuple of length two. The predictions of class larger than two will trigger this error.

Hope this helps, thanks.

**Comment by xkyi** [comment]
First, there are two classes in my custom dataset, and it's weird that  the `cfg.num_classes` printed in train.py 
```
if args.dataset is not None:
    set_dataset(args.dataset)
    cfg.num_classes = len(cfg.dataset.class_names) + 1  # FIXME: this could be better handled
    print('num_classes: ', cfg.num_classes)
```
is the same as the  `cfg.num_classes`  printed in eval.py
```
    img_numpy = (img_gpu * 255).byte().cpu().numpy()
    print(len(cfg.dataset.class_names) + 1)

    if args.display_text or args.display_bboxes:
        for j in reversed(range(num_dets_to_consider)):
            x1, y1, x2, y2 = boxes[j, :]
            color = get_color(j)
            score = scores[j]

            if args.display_bboxes:
                cv2.rectangle(img_numpy, (x1, y1), (x2, y2), color, 1)

            if args.display_text:
                _class = cfg.dataset.class_names[classes[j]]
```
they are all equal to 3.

Besides, my dataset config is shown as follows
```
my_custom_dataset = dataset_base.copy({
    'name': 'My Dataset',

    'train_images': '/data/train',
    'train_info':   '/data/annotations/train_annos.json',

    'valid_images': '/data/val',
    'valid_info':   '/data/annotations/val_annos.json',

    'has_gt': True,
    'class_names': ('label1', 'label2'),

    # below is only needed for YTVIS-style video dataset.

    # whether samples all frames or key frames only.
    'use_all_frames': False,

    # the following four lines define the frame sampling strategy for the given dataset.
    'frame_offset_lb': 1,
    'frame_offset_ub': 4,
    'frame_offset_multiplier': 1,
    'all_frame_direction': 'allway',

    # 1 of K frames is annotated
    'images_per_video': 5,

    # declares a video dataset
    'is_video': False
})
```
And, train code is `python3 train.py --config=yolact_edge_config --dataset=my_custom_dataset`
After 124 epoch, the mAP result is
```
       |  all  |  .50  |  .55  |  .60  |  .65  |  .70  |  .75  |  .80  |  .85  |  .90  |  .95  |
-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+
   box | 44.93 | 49.38 | 48.90 | 48.90 | 48.90 | 48.39 | 48.39 | 48.28 | 47.62 | 45.63 | 14.88 |
  mask | 47.82 | 49.38 | 49.38 | 49.37 | 49.37 | 48.82 | 48.34 | 48.26 | 47.65 | 46.21 | 41.39 |
-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+
```

**Comment by haotian-liu** [comment]
Could you verify the cfg.num_classes in both `yolact_edge_config` and `yolact_edge_pytorch_config` (literally all the configs you use to train and evaluate.)? This will control how the model initialize the PredictionModule (which makes class prediction).

**Comment by xkyi** [comment]
OK, I thought when I use `--dataset=my_custom_dataset` the num_classes can be calculated by
 ```
yolact_base_config = coco_base_config.copy({
    'name': 'yolact_base',

    # Dataset stuff
    'dataset': coco2017_dataset,
    'num_classes': len(coco2017_dataset.class_names) + 1,
```
Thus, the `yolact_edge_config` and `yolact_edge_pytorch_config` I wrote were
```
yolact_edge_config = yolact_base_config.copy({
    'name': 'yolact_edge',

    'torch2trt_max_calibration_images': 100,
    'torch2trt_backbone_int8': True,
    'torch2trt_protonet_int8': True,
    'torch2trt_fpn': True,
    'torch2trt_prediction_module': True,
})
```
```
yolact_edge_pytorch_config = yolact_edge_config.copy({
    'name': 'yolact_edge_pytorch',
    'torch2trt_backbone': False,
    'torch2trt_backbone_int8': False,
    'torch2trt_protonet': False,
    'torch2trt_protonet_int8': False,
    'torch2trt_fpn': False,
    'torch2trt_fpn_int8': False,
    'torch2trt_prediction_module': False,
    'torch2trt_prediction_module_int8': False,
})
```
Next, I will try to add the 'num_classes': 3 in both `yolact_edge_config` and `yolact_edge_pytorch_config`

**Comment by xkyi** [comment]
The error is solved by adding the 'num_classes' in both `yolact_edge_config` and `yolact_edge_pytorch_config`. Thanks for helping!
