### ISSUE TITLE
Out of memory problem

### ISSUE THREAD

**Issue by batselem** [haotian-liu/yolact_edge#101]
**Describe the bug**
Hi, I got out of memory problem when I run eval.py on coco dataset.

**To Reproduce**

`python eval.py --trained_model=weights/yolact_edge_54_800000.pth --benchmark --max_images=1000`

**Expected behavior**
How much memory does it require to test the yolact 54 model?

**Full logs**
```
(base) sde@sde-C246M-WU4:~/yolact_edge$ python eval.py --trained_model=weights/yolact_edge_54_800000.pth --benchmark --max_images=1000
Config not specified. Parsed yolact_edge_config from the file name.

loading annotations into memory...
Done (t=0.32s)
creating index...
index created!
[04/13 09:57:08 yolact.eval]: Loading model...
[04/13 09:57:10 yolact.eval]: Model loaded.
[04/13 09:57:10 yolact.eval]: Converting to TensorRT...
[04/13 09:57:17 yolact.eval]: Converting backbone to TensorRT...
[TensorRT] ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
[TensorRT] ERROR: FAILED_ALLOCATION: std::exception
[TensorRT] ERROR: Context could not be created.
Traceback (most recent call last):
  File "eval.py", line 1275, in <module>
    convert_to_tensorrt(net, cfg, args, transform=BaseTransform())
  File "/home/sde/yolact_edge/utils/tensorrt.py", line 156, in convert_to_tensorrt
    net.to_tensorrt_backbone(cfg.torch2trt_backbone_int8, calibration_dataset=calibration_dataset, batch_size=args.trt_batch_size)
  File "/home/sde/yolact_edge/yolact.py", line 1501, in to_tensorrt_backbone
    self.trt_load_if("backbone", trt_fn, [x], int8_mode, batch_size=batch_size)
  File "/home/usr/yolact_edge/yolact.py", line 1483, in trt_load_if
    module = trt_fn(module, trt_fn_params)
  File "/home/sde/anaconda3/lib/python3.7/site-packages/torch2trt-0.2.0-py3.7-linux-x86_64.egg/torch2trt/torch2trt.py", line 566, in torch2trt
    engine = builder.build_cuda_engine(network)
IndexError: _Map_base::at
```

**Environment:**
 - OS: Ubuntu 18.04
 - GPU: RTX 2060 with 6G memory
 - CUDA Version: 11.1

**Comment by haotian-liu** [comment]
Try setting a smaller set of calib-image: `cfg.torch2trt_max_calibration_images = 5`.

**Comment by batselem** [comment]
Where can I set this parameter? Can I set it in yolact_edge/data/config.py, as follows?

```
yolact_edge_config = yolact_base_config.copy({
    'name': 'yolact_edge',
    'torch2trt_max_calibration_images': 5,
    'torch2trt_backbone_int8': True,
    'torch2trt_protonet_int8': True,
    'torch2trt_fpn': True,
    'torch2trt_prediction_module': True,
})
```

**Comment by haotian-liu** [comment]
Yes you can.

**Comment by batselem** [comment]
Okay it worked. Thanks.

**Comment by batselem** [comment]
Does it affect the  performance (accuracy, map etc)?

**Comment by haotian-liu** [comment]
It has negligible difference -- you can refer to TABLE VI (a) in our paper.
