### ISSUE TITLE
TensorRT FP16 performs significantly worse than FP32, while INT8 gives RuntimeError: The size of tensor a (69) must match the size of tensor b (100) at non-singleton dimension 2

### ISSUE THREAD

**Issue by DableUTeeF** [haotian-liu/yolact_edge#123]
**Describe the bug**
I trained my model using custom dataset with 800x800 input size. The FP32 result is fantastic with 0.8 image/second speed in the Jetson XAVIER NX. 

The FP16 with `--use_fp16_tensorrt --use_tensorrt_safe_mode` gives almost completely random result, the boxes are not even in the correct place and confidences are very low at 0.05-0.07. I can't upload the images due to NDA unfortunately.

FP16 withhout `--use_tensorrt_safe_mode` gives me this error
```
Traceback (most recent call last):
  File "eval.py", line 1281, in <module>
    evaluate(net, dataset)
  File "eval.py", line 917, in evaluate
    evalimages(net, inp, out, detections=detections)
  File "eval.py", line 638, in evalimages
    evalimage(net, path, out_path, detections=detections, image_id=str(i))
  File "eval.py", line 597, in evalimage
    preds = net(batch, extras=extras)["pred_outs"]
  File "/home/ton/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ton/pig/yolact_edge/yolact.py", line 1796, in forward
    outs_wrapper["pred_outs"] = self.detect(pred_outs)
  File "/home/ton/pig/yolact_edge/layers/functions/detection.py", line 75, in __call__
    result = self.detect(batch_idx, conf_preds, decoded_boxes, mask_data, inst_data)
  File "/home/ton/pig/yolact_edge/layers/functions/detection.py", line 105, in detect
    boxes, masks, classes, scores = self.fast_nms(boxes, masks, scores, self.nms_thresh, self.top_k)
  File "/home/ton/pig/yolact_edge/layers/functions/detection.py", line 210, in fast_nms
    classes = classes[keep]
IndexError: The shape of the mask [11] at index 0 does not match the shape of the indexed tensor [1, 11] at index 0
```
With 
```
{
    'torch2trt_fpn': False,
    'torch2trt_fpn_int8': False,
}
```
The error is
```
Traceback (most recent call last):
  File "eval.py", line 1281, in <module>
    evaluate(net, dataset)
  File "eval.py", line 908, in evaluate
    evalimage(net, args.image, detections=detections, image_id="0")
  File "eval.py", line 597, in evalimage
    preds = net(batch, extras=extras)["pred_outs"]
  File "/home/ton/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ton/pig/yolact_edge/yolact.py", line 1796, in forward
    outs_wrapper["pred_outs"] = self.detect(pred_outs)
  File "/home/ton/pig/yolact_edge/layers/functions/detection.py", line 71, in __call__
    conf_preds = conf_data.view(batch_size, num_priors, self.num_classes).transpose(2, 1).contiguous()
RuntimeError: shape '[1, 40029, 2]' is invalid for input of size 38496
```

The one without `--use_fp16_tensorrt`, presumably INT8, gives this error regardless of `--use_tensorrt_safe_mode`.
```
Traceback (most recent call last):
  File "eval.py", line 1276, in <module>
    convert_to_tensorrt(net, cfg, args, transform=BaseTransform())
  File "/home/ton/pig/yolact_edge/utils/tensorrt.py", line 160, in convert_to_tensorrt
    net.to_tensorrt_protonet(cfg.torch2trt_protonet_int8, calibration_dataset=calibration_protonet_dataset, batch_size=args.trt_batch_size)
  File "/home/ton/pig/yolact_edge/yolact.py", line 1513, in to_tensorrt_protonet
    self.trt_load_if("proto_net", trt_fn, [x], int8_mode, batch_size=batch_size)
  File "/home/ton/pig/yolact_edge/yolact.py", line 1482, in trt_load_if
    module = trt_fn(module, trt_fn_params)
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.2.0-py3.6-linux-aarch64.egg/torch2trt/torch2trt.py", line 566, in torch2trt
    engine = builder.build_cuda_engine(network)
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.2.0-py3.6-linux-aarch64.egg/torch2trt/calibration.py", line 51, in get_batch
    buffer[i].copy_(tensor)
RuntimeError: The size of tensor a (69) must match the size of tensor b (100) at non-singleton dimension 2
```
**To Reproduce**
```
python eval.py --trained_model=snapshots/yolact_edge_30_7400.pth --image "/home/ton/pig/image/val/output 0564.jpg" --top_k=100 --use_fp16_tensorrt --use_tensorrt_safe_mode
```

**Environment:**
 - OS: [e.g. Ubuntu 18.04]
 - Jetson XAVIER NX

I found #38 that looks like a similar problem. But it doesn't solve mine.

**Comment by haotian-liu** [comment]
Did you change the input sizes for the images? There seems to be some size mismatches in converting the model to TensorRT.

**Comment by DableUTeeF** [comment]
Actually I solved it by just use 550. I forget to close this.

But such small images had pretty bad accuracy though.

**Comment by haotian-liu** [comment]
You can change the `input_sizes` for converting the TensorRT modules, with respect to your image size. [Here](https://github.com/haotian-liu/yolact_edge/blob/master/yolact_edge/yolact.py#L560) is one of the example location.

**Comment by beanlee999** [comment]
Hi,

I encountered the same error when using int trt conversion as well. For the image input_sizes, what does each of the integer values means?  Thank you!

        input_sizes = [
                (1, 256, 69, 69),
                (1, 256, 35, 35),
                (1, 256, 18, 18),
                (1, 256, 9, 9),
                (1, 256, 5, 5),
        ]

![image](https://user-images.githubusercontent.com/48181638/160737544-b63a259a-8842-4b28-865e-a7041d0abd96.png)

**Comment by beanlee999** [comment]
Hi,

I encountered the same error when using int trt conversion as well. For the image input_sizes, what does each of the integer values means? Thank you!

    input_sizes = [
            (1, 256, 69, 69),
            (1, 256, 35, 35),
            (1, 256, 18, 18),
            (1, 256, 9, 9),
            (1, 256, 5, 5),
    ]
