### ISSUE TITLE
Train Error: ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by xieys** [haotian-liu/yolact_edge#132]
**config.py**
```
my_custom_dataset = dataset_base.copy({
    'name': 'My Dataset',

    'train_images': '/home/xie/桌面/lyw/data_coco',
    'train_info':   '/home/xie/桌面/lyw/data_coco/annotations.json',

    'valid_images': '/home/xie/桌面/lyw/data_coco',
    'valid_info':   '/home/xie/桌面/lyw/data_coco/annotations.json',

    'has_gt': True,
    'class_names': ('cat','dog'),
 #   'label_map':{1:1,2:2}

    # below is only needed for YTVIS-style video dataset.

    # whether samples all frames or key frames only.
    'use_all_frames': False,

    # the following four lines define the frame sampling strategy for the given dataset.
    'frame_offset_lb': 1,
    'frame_offset_ub': 4,
    'frame_offset_multiplier': 1,
    'all_frame_direction': 'allway',

    # 1 of K frames is annotated
    'images_per_video': 5,

    # declares a video dataset
    'is_video': True
})
```

**training command**
```
python train.py --config=yolact_base_config --batch_size=2 --num_workers=0
```

**error**
```
[07/30 19:35:55 yolact.train]: Args: train.py --config=yolact_base_config --batch_size=2 --num_workers=0
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
[07/30 19:35:56 yolact.train]: Initializing weights...
[07/30 19:35:56 yolact.train]: Begin training!
/home/xie/桌面/lyw/yolact_edge/yolact_edge/utils/augmentations.py:414: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  mode = random.choice(self.sample_options)
Traceback (most recent call last):
  File "train.py", line 707, in <module>
    train(0, args=args)
  File "train.py", line 441, in train
    images, annots = frame
ValueError: too many values to unpack (expected 2)
```

**environment:**
 - OS: [Ubuntu 20.04]
 - GPU: [RTX 3060]
 - CUDA Version [11.2]

**Comment by haotian-liu** [comment]
It seems that you are training on an image dataset, while declaring it as the video dataset. Please set `is_video=False` (or simply remove items below the comment `# below is only needed for YTVIS-style video dataset`.

**Comment by haotian-liu** [comment]
I am closing this issue for now due to inactivity. If there are any further questions that I could help with, please feel free to reopen, thanks.
