### ISSUE TITLE
yolact_edge测试错误

### ISSUE THREAD

**Issue by qzsrh** [haotian-liu/yolact_edge#146]
yolact_edge测试错误

运行的命令行为：python eval.py --use_fp16_tensorrt

**Expected behavior**

我在运行 eval.py的时候出现以下错误：
Traceback (most recent call last):
  File "eval.py", line 1280, in <module>
    evaluate(net, dataset)
  File "eval.py", line 925, in evaluate
    savevideo(net, inp, out)
  File "eval.py", line 859, in savevideo
    net_outs = net(batch, extras=extras)
  File "/home/zhangsai/.conda/envs/yolactedg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zhangsai/yolact_edgetest/yolact_edge/yolact.py", line 1795, in forward
    outs_wrapper["pred_outs"] = self.detect(pred_outs)
  File "/home/zhangsai/yolact_edgetest/yolact_edge/layers/functions/detection.py", line 75, in __call__
    result = self.detect(batch_idx, conf_preds, decoded_boxes, mask_data, inst_data)
  File "/home/zhangsai/yolact_edgetest/yolact_edge/layers/functions/detection.py", line 105, in detect
    boxes, masks, classes, scores = self.fast_nms(boxes, masks, scores, self.nms_thresh, self.top_k)
  File "/home/zhangsai/yolact_edgetest/yolact_edge/layers/functions/detection.py", line 210, in fast_nms
    classes = classes[keep]
IndexError: The shape of the mask [1] at index 0 does not match the shape of the indexed tensor [2, 1] at index 0
针对这个问题，希望得到您的解答。
**Environment:**
 - OS: [ Ubuntu 18.04]
 - GPU: [ RTX 2080 Ti *4]
 - CUDA Version [11.1]

**Comment by qzsrh** [comment]
python eval.py --use_tensorrt_safe_mode已解决
