### ISSUE TITLE
nvrtc compilation failed

### ISSUE THREAD

**Issue by venje-zhu** [haotian-liu/yolact_edge#165]
你好，我在运行eval代码时，遇到这个错误：
`
(pytorch1.9) root@localhost:/code/video_instance_segmentation/yolact_edge-master# python eval.py --trained_model=weights/yolact_edge_vid_resnet50_847_50000.pth --score_threshold=0.3 --top_k=100 --video_multiframe=2 --trt_batch_size 2 --video=001.mp4 
Config not specified. Parsed yolact_edge_vid_resnet50_config from the file name.

[11/29 10:35:40 yolact.eval]: Loading model...
[11/29 10:35:44 yolact.eval]: Model loaded.
[11/29 10:35:44 yolact.eval]: Converting to TensorRT...
/root/anaconda3/envs/pytorch1.8/lib/python3.6/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
Traceback (most recent call last):
  File "eval.py", line 1275, in <module>
    convert_to_tensorrt(net, cfg, args, transform=BaseTransform())
  File "/code/video_instance_segmentation/yolact_edge-master/yolact_edge/utils/tensorrt.py", line 106, in convert_to_tensorrt
    "moving_statistics": None
  File "/root/anaconda3/envs/pytorch1.8/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/code/video_instance_segmentation/yolact_edge-master/yolact_edge/yolact.py", line 1795, in forward
    outs_wrapper["pred_outs"] = self.detect(pred_outs)
  File "/code/video_instance_segmentation/yolact_edge-master/yolact_edge/layers/functions/detection.py", line 74, in __call__
    decoded_boxes = decode(loc_data[batch_idx], prior_data)
RuntimeError: nvrtc: error: failed to load builtins for compute_75.
nvrtc compilation failed: 

#define NAN __int_as_float(0x7fffffff)
#define POS_INFINITY __int_as_float(0x7f800000)
#define NEG_INFINITY __int_as_float(0xff800000)

template<typename T>
__device__ T maximum(T a, T b) {
  return isnan(a) ? a : (a > b ? a : b);
}

template<typename T>
__device__ T minimum(T a, T b) {
  return isnan(a) ? a : (a < b ? a : b);
}

extern "C" __global__
void fused_mul_mul_add_mul_exp_mul_cat(float* t_, float* t__, float* t___, float* t____, float* aten_cat) {
{
  if (512 * blockIdx.x + threadIdx.x<76992 ? 1 : 0) {
    aten_cat[512 * blockIdx.x + threadIdx.x] = (((512 * blockIdx.x + threadIdx.x) % 4<2 ? 1 : 0) ? (__ldg(t___ + 512 * blockIdx.x + threadIdx.x)) + (float)((double)(__ldg(t____ + 512 * blockIdx.x + threadIdx.x)) * 0.1) * (__ldg(t_ + 512 * blockIdx.x + threadIdx.x)) : (__ldg(t_ + (512 * blockIdx.x + threadIdx.x) - 2)) * (expf((float)((double)(__ldg(t__ + (512 * blockIdx.x + threadIdx.x) - 2)) * 0.2))));
  }
}
}
`
系统环境为：
- pytorch1.9.0
- torchvision 0.10.0
- cuda 10.2
- cudnn 8.0.0
其他的如TensorRT和torch2rt都是安装安装文档中进行的。
请问这是因为pytorch版本过高导致的吗？

**Comment by haotian-liu** [comment]
It seems that some packages are not installed / compiled correctly.  Please try with the recommended env first, thank you!

**Comment by zhoufqing** [comment]
请问您解决这个问题了，我也遇到了这个问题
