### ISSUE TITLE
RuntimeError: The expanded size of the tensor (20079) must match the existing size (19248) at non-singleton dimension 1.  Target sizes: [8, 20079, 4].  Tensor sizes: [8, 19248, 1]

### ISSUE THREAD

**Issue by lief1117** [haotian-liu/yolact_edge#176]
@haotian-liu 
Hi,I use my own dataset to train, I encounter the error below after using 'sudo python3 'train.py', which part may be wrong? every clue is useful, thanks a lot.

Traceback (most recent call last):
  File "train.py", line 707, in <module>
    train(0, args=args)
  File "train.py", line 433, in train
    losses = backward_and_log(run_name, net_outs, targets, masks, num_crowds)
  File "train.py", line 325, in backward_and_log
    losses = criterion(out, targets, masks, num_crowds)
  File "/home/lief/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lief/yolact_edge/yolact_edge/layers/modules/multibox_loss.py", line 137, in forward
    pos_idx = pos.unsqueeze(pos.dim()).expand_as(loc_data)
RuntimeError: The expanded size of the tensor (20079) must match the existing size (19248) at non-singleton dimension 1.  Target sizes: [8, 20079, 4].  Tensor sizes: [8, 19248, 1]

**Comment by lief1117** [comment]
it turn out that some disk of my GPU is not working.
