### ISSUE TITLE
Error while evaluating model trained on custom dataset

### ISSUE THREAD

**Issue by akankshabaranwal** [haotian-liu/yolact_edge#192]
**Describe the bug**
I am running into the error during evaluation of a model trained on custom dataset :     ```File "/home/snake/abaranwal/stemHarvest/yolact_edge/yolact_edge/layers/functions/detection.py", line 210, in fast_nms
    classes = classes[keep]
IndexError: too many indices for tensor of dimension 2```
Could someone help understand what is the issue here ?

**To Reproduce**
The modifications I made in the config file are: 
```
yolact_new_resnet50_config = yolact_edge_resnet50_config.copy({
    'name': 'new_mixed_yolact_edge',
    'dataset': new_dataset,
    'num_classes': 4,
    'gamma': 0.1,
    'lr_steps': (1500, 3000, 6000),
    })
```

Command used for training is: `python3 train.py --config=yolact_grape_resnet50_config --resume=weights/grape_mixed_yolact_edge_5228_800000.pth --lr=0.00005 --batch_size=4 --num_workers=2`

Command used for evaluation is: `python3 eval.py --trained_model=weights/new_mixed_yolact_edge_5228_800000.pth --score_threshold=0.1 --top_k=10 --video=videos/videoL.gif --config=yolact_new_resnet50_config`

**Full logs**

```
[05/23 13:22:39 yolact.eval]: Loading model...
WARNING [05/23 13:22:45 yolact.model.load]: Some parameters in the checkpoint are not used: backbone.layers.2.6.conv1.weight, backbone.layers.2.6.bn1.weight, backbone.layers.2.6.bn1.bias, backbone.layers.2.6.bn1.running_mean, backbone.layers.2.6.bn1.running_var, backbone.layers.2.6.bn1.num_batches_tracked, backbone.layers.2.6.conv2.weight, backbone.layers.2.6.bn2.weight, backbone.layers.2.6.bn2.bias, backbone.layers.2.6.bn2.running_mean, backbone.layers.2.6.bn2.running_var, backbone.layers.2.6.bn2.num_batches_tracked, backbone.layers.2.6.conv3.weight, backbone.layers.2.6.bn3.weight, backbone.layers.2.6.bn3.bias, backbone.layers.2.6.bn3.running_mean, backbone.layers.2.6.bn3.running_var, backbone.layers.2.6.bn3.num_batches_tracked, backbone.layers.2.7.conv1.weight, backbone.layers.2.7.bn1.weight, backbone.layers.2.7.bn1.bias, backbone.layers.2.7.bn1.running_mean, backbone.layers.2.7.bn1.running_var, backbone.layers.2.7.bn1.num_batches_tracked, backbone.layers.2.7.conv2.weight, backbone.layers.2.7.bn2.weight, backbone.layers.2.7.bn2.bias, backbone.layers.2.7.bn2.running_mean, backbone.layers.2.7.bn2.running_var, backbone.layers.2.7.bn2.num_batches_tracked, backbone.layers.2.7.conv3.weight, backbone.layers.2.7.bn3.weight, backbone.layers.2.7.bn3.bias, backbone.layers.2.7.bn3.running_mean, backbone.layers.2.7.bn3.running_var, backbone.layers.2.7.bn3.num_batches_tracked, backbone.layers.2.8.conv1.weight, backbone.layers.2.8.bn1.weight, backbone.layers.2.8.bn1.bias, backbone.layers.2.8.bn1.running_mean, backbone.layers.2.8.bn1.running_var, backbone.layers.2.8.bn1.num_batches_tracked, backbone.layers.2.8.conv2.weight, backbone.layers.2.8.bn2.weight, backbone.layers.2.8.bn2.bias, backbone.layers.2.8.bn2.running_mean, backbone.layers.2.8.bn2.running_var, backbone.layers.2.8.bn2.num_batches_tracked, backbone.layers.2.8.conv3.weight, backbone.layers.2.8.bn3.weight, backbone.layers.2.8.bn3.bias, backbone.layers.2.8.bn3.running_mean, backbone.layers.2.8.bn3.running_var, backbone.layers.2.8.bn3.num_batches_tracked, backbone.layers.2.9.conv1.weight, backbone.layers.2.9.bn1.weight, backbone.layers.2.9.bn1.bias, backbone.layers.2.9.bn1.running_mean, backbone.layers.2.9.bn1.running_var, backbone.layers.2.9.bn1.num_batches_tracked, backbone.layers.2.9.conv2.weight, backbone.layers.2.9.bn2.weight, backbone.layers.2.9.bn2.bias, backbone.layers.2.9.bn2.running_mean, backbone.layers.2.9.bn2.running_var, backbone.layers.2.9.bn2.num_batches_tracked, backbone.layers.2.9.conv3.weight, backbone.layers.2.9.bn3.weight, backbone.layers.2.9.bn3.bias, backbone.layers.2.9.bn3.running_mean, backbone.layers.2.9.bn3.running_var, backbone.layers.2.9.bn3.num_batches_tracked, backbone.layers.2.10.conv1.weight, backbone.layers.2.10.bn1.weight, backbone.layers.2.10.bn1.bias, backbone.layers.2.10.bn1.running_mean, backbone.layers.2.10.bn1.running_var, backbone.layers.2.10.bn1.num_batches_tracked, backbone.layers.2.10.conv2.weight, backbone.layers.2.10.bn2.weight, backbone.layers.2.10.bn2.bias, backbone.layers.2.10.bn2.running_mean, backbone.layers.2.10.bn2.running_var, backbone.layers.2.10.bn2.num_batches_tracked, backbone.layers.2.10.conv3.weight, backbone.layers.2.10.bn3.weight, backbone.layers.2.10.bn3.bias, backbone.layers.2.10.bn3.running_mean, backbone.layers.2.10.bn3.running_var, backbone.layers.2.10.bn3.num_batches_tracked, backbone.layers.2.11.conv1.weight, backbone.layers.2.11.bn1.weight, backbone.layers.2.11.bn1.bias, backbone.layers.2.11.bn1.running_mean, backbone.layers.2.11.bn1.running_var, backbone.layers.2.11.bn1.num_batches_tracked, backbone.layers.2.11.conv2.weight, backbone.layers.2.11.bn2.weight, backbone.layers.2.11.bn2.bias, backbone.layers.2.11.bn2.running_mean, backbone.layers.2.11.bn2.running_var, backbone.layers.2.11.bn2.num_batches_tracked, backbone.layers.2.11.conv3.weight, backbone.layers.2.11.bn3.weight, backbone.layers.2.11.bn3.bias, backbone.layers.2.11.bn3.running_mean, backbone.layers.2.11.bn3.running_var, backbone.layers.2.11.bn3.num_batches_tracked, backbone.layers.2.12.conv1.weight, backbone.layers.2.12.bn1.weight, backbone.layers.2.12.bn1.bias, backbone.layers.2.12.bn1.running_mean, backbone.layers.2.12.bn1.running_var, backbone.layers.2.12.bn1.num_batches_tracked, backbone.layers.2.12.conv2.weight, backbone.layers.2.12.bn2.weight, backbone.layers.2.12.bn2.bias, backbone.layers.2.12.bn2.running_mean, backbone.layers.2.12.bn2.running_var, backbone.layers.2.12.bn2.num_batches_tracked, backbone.layers.2.12.conv3.weight, backbone.layers.2.12.bn3.weight, backbone.layers.2.12.bn3.bias, backbone.layers.2.12.bn3.running_mean, backbone.layers.2.12.bn3.running_var, backbone.layers.2.12.bn3.num_batches_tracked, backbone.layers.2.13.conv1.weight, backbone.layers.2.13.bn1.weight, backbone.layers.2.13.bn1.bias, backbone.layers.2.13.bn1.running_mean, backbone.layers.2.13.bn1.running_var, backbone.layers.2.13.bn1.num_batches_tracked, backbone.layers.2.13.conv2.weight, backbone.layers.2.13.bn2.weight, backbone.layers.2.13.bn2.bias, backbone.layers.2.13.bn2.running_mean, backbone.layers.2.13.bn2.running_var, backbone.layers.2.13.bn2.num_batches_tracked, backbone.layers.2.13.conv3.weight, backbone.layers.2.13.bn3.weight, backbone.layers.2.13.bn3.bias, backbone.layers.2.13.bn3.running_mean, backbone.layers.2.13.bn3.running_var, backbone.layers.2.13.bn3.num_batches_tracked, backbone.layers.2.14.conv1.weight, backbone.layers.2.14.bn1.weight, backbone.layers.2.14.bn1.bias, backbone.layers.2.14.bn1.running_mean, backbone.layers.2.14.bn1.running_var, backbone.layers.2.14.bn1.num_batches_tracked, backbone.layers.2.14.conv2.weight, backbone.layers.2.14.bn2.weight, backbone.layers.2.14.bn2.bias, backbone.layers.2.14.bn2.running_mean, backbone.layers.2.14.bn2.running_var, backbone.layers.2.14.bn2.num_batches_tracked, backbone.layers.2.14.conv3.weight, backbone.layers.2.14.bn3.weight, backbone.layers.2.14.bn3.bias, backbone.layers.2.14.bn3.running_mean, backbone.layers.2.14.bn3.running_var, backbone.layers.2.14.bn3.num_batches_tracked, backbone.layers.2.15.conv1.weight, backbone.layers.2.15.bn1.weight, backbone.layers.2.15.bn1.bias, backbone.layers.2.15.bn1.running_mean, backbone.layers.2.15.bn1.running_var, backbone.layers.2.15.bn1.num_batches_tracked, backbone.layers.2.15.conv2.weight, backbone.layers.2.15.bn2.weight, backbone.layers.2.15.bn2.bias, backbone.layers.2.15.bn2.running_mean, backbone.layers.2.15.bn2.running_var, backbone.layers.2.15.bn2.num_batches_tracked, backbone.layers.2.15.conv3.weight, backbone.layers.2.15.bn3.weight, backbone.layers.2.15.bn3.bias, backbone.layers.2.15.bn3.running_mean, backbone.layers.2.15.bn3.running_var, backbone.layers.2.15.bn3.num_batches_tracked, backbone.layers.2.16.conv1.weight, backbone.layers.2.16.bn1.weight, backbone.layers.2.16.bn1.bias, backbone.layers.2.16.bn1.running_mean, backbone.layers.2.16.bn1.running_var, backbone.layers.2.16.bn1.num_batches_tracked, backbone.layers.2.16.conv2.weight, backbone.layers.2.16.bn2.weight, backbone.layers.2.16.bn2.bias, backbone.layers.2.16.bn2.running_mean, backbone.layers.2.16.bn2.running_var, backbone.layers.2.16.bn2.num_batches_tracked, backbone.layers.2.16.conv3.weight, backbone.layers.2.16.bn3.weight, backbone.layers.2.16.bn3.bias, backbone.layers.2.16.bn3.running_mean, backbone.layers.2.16.bn3.running_var, backbone.layers.2.16.bn3.num_batches_tracked, backbone.layers.2.17.conv1.weight, backbone.layers.2.17.bn1.weight, backbone.layers.2.17.bn1.bias, backbone.layers.2.17.bn1.running_mean, backbone.layers.2.17.bn1.running_var, backbone.layers.2.17.bn1.num_batches_tracked, backbone.layers.2.17.conv2.weight, backbone.layers.2.17.bn2.weight, backbone.layers.2.17.bn2.bias, backbone.layers.2.17.bn2.running_mean, backbone.layers.2.17.bn2.running_var, backbone.layers.2.17.bn2.num_batches_tracked, backbone.layers.2.17.conv3.weight, backbone.layers.2.17.bn3.weight, backbone.layers.2.17.bn3.bias, backbone.layers.2.17.bn3.running_mean, backbone.layers.2.17.bn3.running_var, backbone.layers.2.17.bn3.num_batches_tracked, backbone.layers.2.18.conv1.weight, backbone.layers.2.18.bn1.weight, backbone.layers.2.18.bn1.bias, backbone.layers.2.18.bn1.running_mean, backbone.layers.2.18.bn1.running_var, backbone.layers.2.18.bn1.num_batches_tracked, backbone.layers.2.18.conv2.weight, backbone.layers.2.18.bn2.weight, backbone.layers.2.18.bn2.bias, backbone.layers.2.18.bn2.running_mean, backbone.layers.2.18.bn2.running_var, backbone.layers.2.18.bn2.num_batches_tracked, backbone.layers.2.18.conv3.weight, backbone.layers.2.18.bn3.weight, backbone.layers.2.18.bn3.bias, backbone.layers.2.18.bn3.running_mean, backbone.layers.2.18.bn3.running_var, backbone.layers.2.18.bn3.num_batches_tracked, backbone.layers.2.19.conv1.weight, backbone.layers.2.19.bn1.weight, backbone.layers.2.19.bn1.bias, backbone.layers.2.19.bn1.running_mean, backbone.layers.2.19.bn1.running_var, backbone.layers.2.19.bn1.num_batches_tracked, backbone.layers.2.19.conv2.weight, backbone.layers.2.19.bn2.weight, backbone.layers.2.19.bn2.bias, backbone.layers.2.19.bn2.running_mean, backbone.layers.2.19.bn2.running_var, backbone.layers.2.19.bn2.num_batches_tracked, backbone.layers.2.19.conv3.weight, backbone.layers.2.19.bn3.weight, backbone.layers.2.19.bn3.bias, backbone.layers.2.19.bn3.running_mean, backbone.layers.2.19.bn3.running_var, backbone.layers.2.19.bn3.num_batches_tracked, backbone.layers.2.20.conv1.weight, backbone.layers.2.20.bn1.weight, backbone.layers.2.20.bn1.bias, backbone.layers.2.20.bn1.running_mean, backbone.layers.2.20.bn1.running_var, backbone.layers.2.20.bn1.num_batches_tracked, backbone.layers.2.20.conv2.weight, backbone.layers.2.20.bn2.weight, backbone.layers.2.20.bn2.bias, backbone.layers.2.20.bn2.running_mean, backbone.layers.2.20.bn2.running_var, backbone.layers.2.20.bn2.num_batches_tracked, backbone.layers.2.20.conv3.weight, backbone.layers.2.20.bn3.weight, backbone.layers.2.20.bn3.bias, backbone.layers.2.20.bn3.running_mean, backbone.layers.2.20.bn3.running_var, backbone.layers.2.20.bn3.num_batches_tracked, backbone.layers.2.21.conv1.weight, backbone.layers.2.21.bn1.weight, backbone.layers.2.21.bn1.bias, backbone.layers.2.21.bn1.running_mean, backbone.layers.2.21.bn1.running_var, backbone.layers.2.21.bn1.num_batches_tracked, backbone.layers.2.21.conv2.weight, backbone.layers.2.21.bn2.weight, backbone.layers.2.21.bn2.bias, backbone.layers.2.21.bn2.running_mean, backbone.layers.2.21.bn2.running_var, backbone.layers.2.21.bn2.num_batches_tracked, backbone.layers.2.21.conv3.weight, backbone.layers.2.21.bn3.weight, backbone.layers.2.21.bn3.bias, backbone.layers.2.21.bn3.running_mean, backbone.layers.2.21.bn3.running_var, backbone.layers.2.21.bn3.num_batches_tracked, backbone.layers.2.22.conv1.weight, backbone.layers.2.22.bn1.weight, backbone.layers.2.22.bn1.bias, backbone.layers.2.22.bn1.running_mean, backbone.layers.2.22.bn1.running_var, backbone.layers.2.22.bn1.num_batches_tracked, backbone.layers.2.22.conv2.weight, backbone.layers.2.22.bn2.weight, backbone.layers.2.22.bn2.bias, backbone.layers.2.22.bn2.running_mean, backbone.layers.2.22.bn2.running_var, backbone.layers.2.22.bn2.num_batches_tracked, backbone.layers.2.22.conv3.weight, backbone.layers.2.22.bn3.weight, backbone.layers.2.22.bn3.bias, backbone.layers.2.22.bn3.running_mean, backbone.layers.2.22.bn3.running_var, backbone.layers.2.22.bn3.num_batches_tracked
[05/23 13:22:45 yolact.eval]: Model loaded.
[05/23 13:22:45 yolact.eval]: Converting to TensorRT...
[05/23 13:22:45 yolact.eval]: Converting backbone to TensorRT...
[05/23 13:22:47 yolact.eval]: Converting protonet to TensorRT...
[05/23 13:22:47 yolact.eval]: Converting FPN to TensorRT...
[05/23 13:22:47 yolact.eval]: Converting PredictionModule to TensorRT...
[05/23 13:23:01 yolact.eval]: Converted to TensorRT.
Initializing model... Traceback (most recent call last):
  File "eval.py", line 1280, in <module>
    evaluate(net, dataset)
  File "eval.py", line 927, in evaluate
    evalvideo(net, args.video)
  File "eval.py", line 767, in evalvideo
    eval_network(transform_frame(get_next_frame(vid)))
  File "eval.py", line 700, in eval_network
    net_outs = net(imgs, extras=extras)
  File "/home/snake/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/snake/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/snake/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/snake/abaranwal/stemHarvest/yolact_edge/yolact_edge/yolact.py", line 1795, in forward
    outs_wrapper["pred_outs"] = self.detect(pred_outs)
  File "/home/snake/abaranwal/stemHarvest/yolact_edge/yolact_edge/layers/functions/detection.py", line 75, in __call__
    result = self.detect(batch_idx, conf_preds, decoded_boxes, mask_data, inst_data)
  File "/home/snake/abaranwal/stemHarvest/yolact_edge/yolact_edge/layers/functions/detection.py", line 105, in detect
    boxes, masks, classes, scores = self.fast_nms(boxes, masks, scores, self.nms_thresh, self.top_k)
  File "/home/snake/abaranwal/stemHarvest/yolact_edge/yolact_edge/layers/functions/detection.py", line 210, in fast_nms
    classes = classes[keep]
IndexError: too many indices for tensor of dimension 2

```

**Environment:**
 - OS: [Ubuntu 18.04]
 - GPU: [Jetson Xavier]
 - CUDA Version [e.g. 10.2]

**Comment by akankshabaranwal** [comment]
Running it with --use_tensorrt_safe_mode resolved the issue.
