### ISSUE TITLE
ZeroDivisionError:division by zero

### ISSUE THREAD

**Issue by hlbtjdws1** [haotian-liu/yolact_edge#199]
[08/22 22:09:35 yolact.train]: Args: train.py --config=yolact_edge_strawberry_config
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
[08/22 22:09:36 yolact.train]: Initializing weights...
Traceback (most recent call last):
  File "train.py", line 708, in <module>
    train(0, args=args)
  File "train.py", line 286, in train
    num_epochs = math.ceil(cfg.max_iter / epoch_size)
ZeroDivisionError: division by zero

train on pictures

**Comment by Wong-denis** [comment]
I also get the same error, which i haven't seen before 
I guess my problem is because i set my 'max_iter' to 800
If I set it higher than 2000 the error is gone
or you can set  
--batch_size=2
(change batch size also work for me)

**Comment by hlbtjdws1** [comment]
Solved already. epoch_size = len(dataset) // args.batch_size // args.num_gpus so that means batch_size should be smaller than len(dataset) in order to get a number >= 1
