### ISSUE TITLE
Jetsno Xavier NX docker build error

### ISSUE THREAD

**Issue by achbogga** [haotian-liu/yolact_edge#202]
**Describe the bug**
```
Cloning into 'torch2trt'...
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    import torch
  File "/usr/local/lib/python3.6/dist-packages/torch/__init__.py", line 195, in <module>
    _load_global_deps()
  File "/usr/local/lib/python3.6/dist-packages/torch/__init__.py", line 148, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcurand.so.10: cannot open shared object file: No such file or directory
The command '/bin/sh -c git clone https://github.com/NVIDIA-AI-IOT/torch2trt &&    cd torch2trt &&    python setup.py install --plugins' returned a non-zero code: 1
```

**To Reproduce**
```
cd docker
sudo docker build -t yolact_edge -f Dockerfile.xavier  .
```

**Expected behavior**
expected jetson container to be built properly

**Full logs**
```
ARG L4T_IMAGE=nvcr.io/nvidia/l4t-pytorch:r32.6.1-pth1.8-py3
ARG JETSON_PLATFORM=t194

```
**Environment:**
 - OS: Jetpack 6.1
 - GPU: Xavier NX
 - CUDA Version: 10.2

**Additional context**

**Comment by achbogga** [comment]
@haotian-liu

**Comment by gautam-suryawanshi** [comment]
@achbogga were you able to solve this issue?

**Comment by abhishek-nair-conxai** [comment]
Replace lines 35 to 46 in the Docker file with the below lines. Installing nvidia-l4t-core and then nvidia-jetpack will help solve the issue.
``` 
    mkdir -p /opt/nvidia/l4t-packages/ && \
    touch /opt/nvidia/l4t-packages/.nv-l4t-disable-boot-fw-update-in-preinstall && \
    apt-get update && \
    apt-get install -y --no-install-recommends nvidia-l4t-core -o Dpkg::Options::="--force-confold"&& \
    apt-get install --no-install-recommends -y nvidia-jetpack build-essential make cmake cmake-curses-gui unzip \
                        git g++ pkg-config curl \
                        python3-dev python3-testresources python3-pip \
                        python3-numpy python3-tk ffmpeg libsm6 libxext6 \
                        libopencv-python libopencv-dev && \
    apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN ln -svf /usr/bin/python3 /usr/bin/python
RUN python -m pip install --upgrade --force pip

# # Install dependencies
RUN pip install cython pillow matplotlib GitPython termcolor tensorboard packaging
````
