### ISSUE TITLE
Jetsno Nano docker build error 

### ISSUE THREAD

**Issue by gautam-suryawanshi** [haotian-liu/yolact_edge#228]
**Describe the bug**
Cloning into 'torch2trt'...
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    import torch
  File "/usr/local/lib/python3.6/dist-packages/torch/__init__.py", line 196, in <module>
    _load_global_deps()
  File "/usr/local/lib/python3.6/dist-packages/torch/__init__.py", line 149, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcurand.so.10: cannot open shared object file: No such file or directory

**To Reproduce**
cd docker
sudo docker build -t yolact_edge -f Dockerfile.xavier  .

**Expected behavior**
expected jetson container to be built properly

**Full logs**
ARG L4T_IMAGE=nvcr.io/nvidia/l4t-pytorch:r32.7.1-pth1.10-py3
ARG JETSON_PLATFORM=t210

**Environment:**
JETSON NANO 
Jetpack 7.1

**Additional context**

**Comment by gautam-suryawanshi** [comment]
[https://forums.developer.nvidia.com/t/jetson-voice-docker-image-run-gives-oserror-libcurand-so-10-cannot-open-shared-object-file-no-such-file-or-directory/194897](url)

If this does not work, try installing all the dependencies manually inside docker container, worked for me.
