### ISSUE TITLE
Error when resizing image for inference using trained model on Jetson TX2 - seeking advice

### ISSUE THREAD

**Issue by dchssk** [haotian-liu/yolact_edge#233]
Hello,

When I try to perform inference by reducing the image size, an error occurs.
```
change_size_config = yolact_edge_config.copy({
    'name': 'change_size_config',
    'dataset': test_dataset,
    'max_iter': 1,
    'lr_steps': (4500, 7500),

    # Image Size
    'max_size': 480,
})
```

I used this to conduct the training:
```
root@nvidia-desktop:/app/yolact_edge# python3 train.py --config=change_size_config --save_folder=/share/test/ --num_workers=0 --resume=/share/test/yolact_edge_54_800000.pth --batch_size=1 --start_iter=0
2023-03-03 14:37:28.798146: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.2
WARNING:tensorflow:Deprecation warnings have been disabled. Set TF_ENABLE_DEPRECATION_WARNINGS=1 to re-enable them.
[03/03 14:37:37 yolact.train]: Args: train.py --config=change_size_config --save_folder=/share/test/ --num_workers=0 --resume=/share/test/yolact_edge_54_800000.pth --batch_size=1 --start_iter=0
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
[03/03 14:37:56 yolact.train]: Resuming training, loading /share/test/yolact_edge_54_800000.pth...
[03/03 14:37:58 yolact.train]: Begin training!
/app/yolact_edge/yolact_edge/utils/augmentations.py:414: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  mode = random.choice(self.sample_options)
[03/03 14:38:12 yolact.train]: eta: 0:00:00  epoch: 0  iter: 0  B: 3.032  M: 7.972  C: 9.760  S: 9.037  T: 29.801  time: 13.694  data_time: 0.000  lr: 0.000100  max_mem: 944M
```

However, when I try to perform inference using the resulting .pth file, an error occurs:
```
root@nvidia-desktop:/app/yolact_edge# python3 eval.py --config=change_size_config --use_fp16_tensorrt --trained_model=/share/test/change_size_config_0_1.pth  --score_threshold=0.3 --top_k=100  --image=/share/test/test.jpg 
[03/03 14:38:57 yolact.eval]: Loading model...
[03/03 14:39:15 yolact.eval]: Model loaded.
[03/03 14:39:15 yolact.eval]: Converting to TensorRT...
[03/03 14:39:15 yolact.eval]: Converting backbone to TensorRT...
[03/03 14:40:23 yolact.eval]: Converting protonet to TensorRT...
[03/03 14:40:34 yolact.eval]: Converting FPN to TensorRT...
Warning: Encountered known unsupported method torch.zeros
[03/03 14:40:49 yolact.eval]: Converting PredictionModule to TensorRT...
[03/03 14:41:14 yolact.eval]: Converted to TensorRT.
[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::1045, condition: profileMinDims.d[i] <= dimensions.d[i]
[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::1045, condition: profileMinDims.d[i] <= dimensions.d[i]
[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::1045, condition: profileMinDims.d[i] <= dimensions.d[i]
```

Has anyone been able to change the size and perform inference successfully?

By the way, here's my environment:

Jetson TX2
nvcr.io/nvidia/l4t-base:r32.4.3

**Comment by dchssk** [comment]
https://github.com/haotian-liu/yolact_edge/issues/37#issuecomment-766462942
I changed not only max_size but also pred_scales, discard_box_height, etc. according to this description.

https://github.com/haotian-liu/yolact_edge/issues/110
https://github.com/haotian-liu/yolact_edge/issues/123
```
input_sizes = [
        (1, 256, 69, 69),
        (1, 256, 35, 35),
        (1, 256, 18, 18),
        (1, 256, 9, 9),
        (1, 256, 5, 5),
]
```

I was told that input_sizes also needed to be changed, so I estimated from the mood of the values that the sizes were P3~P7 and changed them.
I asked ChatGPT about the size.
```
If ResNet101 is used as the backbone and a 350x350 image is input to RetinaNet, the output sizes of P3 to P7 would be as follows:

P3: (44, 44)
P4: (22, 22)
P5: (11, 11)
P6: (6, 6)
P7: (3, 3)
Since ResNet101 is a deeper model with more layers, it can extract more sophisticated feature representations. However, when the input size is smaller, RetinaNet generates smaller feature maps, resulting in smaller output sizes for P3 to P7 compared to when ResNet50 is used as the backbone.
```
```
input_sizes = [
        (1, 256, 44, 44),
        (1, 256, 22, 22),
        (1, 256, 11, 11),
        (1, 256, 6, 6),
        (1, 256, 3, 3),
]
```

However, this still produced an error
```
2023-03-27 08:04:30,624 - INFO - cam1:rtsp://192.168.1.247:8554/mystream1 open
[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::1045, condition: profileMinDims.d[i] <= dimensions.d[i]
[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::1045, condition: profileMinDims.d[i] <= dimensions.d[i]
[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::1045, condition: profileMinDims.d[i] <= dimensions.d[i]
[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::1044, condition: profileMaxDims.d[i] >= dimensions.d[i]
[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::1044, condition: profileMaxDims.d[i] >= dimensions.d[i]
[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::1044, condition: profileMaxDims.d[i] >= dimensions.d[i]
[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::1044, condition: profileMaxDims.d[i] >= dimensions.d[i]
[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::1044, condition: profileMaxDims.d[i] >= dimensions.d[i]
2023-03-27 08:04:31,429 - WARNING - ExternalDeviceSetting exit: <class 'RuntimeError'> shape '[1, 19248, 11]' is invalid for input of size 85338 <traceback object at 0x7ed5d18808>
2023-03-27 08:04:31,434 - INFO - loader exit
2023-03-27 08:04:31,435 - WARNING - AppSetting.ChangeHandler exit: <class 'RuntimeError'> shape '[1, 19248, 11]' is invalid for input of size 85338 <traceback object at 0x7ed5d18808>
Traceback (most recent call last):
  File "/app/parkingdetectcabin/__main__.py", line 28, in <module>
    r = ParkingDetectCabin().main()
  File "/app/parkingdetectcabin/classes/parking_detect_cabin.py", line 112, in main
    result_list = analytics_cabin.detect(frame=frame_dict, disp= (self.app_setting.disp or self.app_setting.web_stream), frame_rate=frame_rate)
  File "/app/parkingdetectcabin/classes/domain/interactor/analytics_cabin.py", line 137, in detect
    detect_result = zip(frame.keys(), frame.values(), [self.model.detect(v[0], verbose=0, camera_index=k) for k, v in frame.items()])
  File "/app/parkingdetectcabin/classes/domain/interactor/analytics_cabin.py", line 137, in <listcomp>
    detect_result = zip(frame.keys(), frame.values(), [self.model.detect(v[0], verbose=0, camera_index=k) for k, v in frame.items()])
  File "/app/parkingdetectcabin/classes/domain/model/segment_model_from_yolact_edge.py", line 247, in detect
    net_outs = self.yolact(batch, extras=extras)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/app/parkingdetectcabin/classes/core/yolact_edge/yolact_edge/yolact.py", line 1802, in forward
    outs_wrapper["pred_outs"] = self.detect(pred_outs)
  File "/app/parkingdetectcabin/classes/core/yolact_edge/yolact_edge/layers/functions/detection.py", line 71, in __call__
    conf_preds = conf_data.view(batch_size, num_priors, self.num_classes).transpose(2, 1).contiguous()
RuntimeError: shape '[1, 19248, 11]' is invalid for input of size 85338
```

**Comment by dchssk** [comment]
I found the following settings listed elsewhere, but they do not work.
```
'pred_scales': [[int(x[0] / yolact_base_config.max_size * 350)] for x in yolact_base_config.backbone.pred_scales],
```

I set up the following and it worked for all sizes except 550
```
    'max_size': 416,
    'discard_box_width': 4 / 416,
    'discard_box_height': 4 / 416,
    'backbone': yolact_base_config.backbone.copy({
        # Must be changed according to the size of the feature map
        'pred_scales': [[floor(x[0] * (416 / yolact_base_config.max_size))] for x in yolact_base_config.backbone.pred_scales],
    }),
```
