### ISSUE TITLE
agx torch nccl not built in

### ISSUE THREAD

**Issue by soohunee** [haotian-liu/yolact_edge#24]
I am using jetson agx xavier.
I have installed torch through this link.

https://forums.developer.nvidia.com/t/pytorch-for-jetson-version-1-7-0-now-available/72048

When I try to train my custom dataset, I get this error.

**Traceback (most recent call last):
  File "train.py", line 744, in <module>
    train(0, args=args)
  File "train.py", line 195, in train
    raise e
  File "train.py", line 191, in train
    rank=rank
  File "/home/jetson/.local/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 432, in init_process_group
    timeout=timeout)
  File "/home/jetson/.local/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 508, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL "
RuntimeError: Distributed package doesn't have NCCL built in**

I have installed NCCL library and checked it is working.
Would it be a problem related to my torch installation ?

**Comment by haotian-liu** [comment]
We do not recommend **training** on Jetson, as it will be slow. Processing speed is optimized for evaluation.
