### ISSUE TITLE
Can't Evaluate on Video

### ISSUE THREAD

**Issue by cyrilzakka** [haotian-liu/yolact_edge#25]
Running the following command to evaluate on video:
`!python eval.py --config=yolact_edge_pytorch_config --coco_transfer --trained_model=weights/yolact_edge_54_800000.pth --score_threshold=0.3 --top_k=100 --video=video.mp4:demo.mp4`
fails with the following error:

```
[01/07 10:30:39 yolact.eval]: Loading model...
/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py:182: UserWarning: 'lat_layers' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
  " but it is a non-constant {}. Consider removing it.".format(name, hint))
/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py:182: UserWarning: 'pred_layers' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
  " but it is a non-constant {}. Consider removing it.".format(name, hint))
/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py:182: UserWarning: 'downsample_layers' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
  " but it is a non-constant {}. Consider removing it.".format(name, hint))
[01/07 10:30:42 yolact.eval]: Model loaded.
Processing Frames  ███████████████████░░░░░░░░░░░    310 /    470 (65.96%)     5.85 fps        Traceback (most recent call last):
  File "eval.py", line 1407, in <module>
    evaluate(net, dataset)
  File "eval.py", line 888, in evaluate
    savevideo(net, inp, out)
  File "eval.py", line 827, in savevideo
    frame = torch.from_numpy(vid.read()[1]).cuda().float()
TypeError: expected np.ndarray (got NoneType)
```

**Comment by cyrilzakka** [comment]
I realize it's because a frame in my video might be corrupt for some reason. The process always stops at frame 310. Going to try 
```
frame = vid.read()[1]
if frame is None:
    continue
frame = torch.from_numpy(frame).cuda().float()
```

instead of:
`frame = torch.Tensor(vid.read()[1]).float().cuda()`
