### ISSUE TITLE
eval with the pretrained model without tensorrt:"assert type(extras) == dict"

### ISSUE THREAD

**Issue by SanjunLiu** [haotian-liu/yolact_edge#28]
It worked when I train with my own datasets, but during the evalution, following errors have happened:
python eval.py --coco_transfer \
    --trained_model=pretrained/yolact_edge_54_800000.pth \
    --score_threshold=0.3 \
    --top_k=100 \
    --image=/datasets/industial_data/Test_Images/12_1598191381_7232635.bmp:output_image.png

Traceback (most recent call last):
  File "eval.py", line 1392, in <module>
    evaluate(net, dataset)
  File "eval.py", line 868, in evaluate
    evalimage(net, inp, out)
  File "eval.py", line 580, in evalimage
    preds = net(batch)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/workspace/dl/yolact_edge/yolact.py", line 1881, in forward
    assert type(extras) == dict
AssertionError

**Comment by SanjunLiu** [comment]
I found extras is None, Why?

**Comment by haotian-liu** [comment]
See #6, and it has been fixed. Please pull the latest code and re-run, thanks.
