### ISSUE TITLE
What channel size does FPN expect?

### ISSUE THREAD

**Issue by cyrilzakka** [haotian-liu/yolact_edge#31]
I've been trying to add a new backbone to this project for the past several days and I have several questions. Would you mind helping me out?

In my `forward(x)` I do the following `return tuple(outs)` where outs has the output of all 31 blocks of my network. In `selected_layers` I specify [22, 26, -1]. This returns the following error:

`Given groups=1, weight of size [256, 512, 1, 1], expected input[8, 1024, 7, 7] to have 512 channels, but got 1024 channels instead`

If I replaced `selected_layers` with just [22, 26], the network trains fine until it hits the following error:
```
[01/17 19:20:14 yolact.train]: eta: 0:00:00  epoch: 0  iter: 0  B: 8.873  M: 57.962  C: 21.055  S: 59.843  T: 147.732  time: 5.293  data_time: 0.000  lr: 0.000100  max_mem: 4405M
[01/17 19:20:17 yolact.eval]: Computing validation mAP (this may take a while)...

Traceback (most recent call last):
  File "train.py", line 746, in <module>
    train(0, args=args)
  File "train.py", line 642, in train
    compute_validation_map(yolact_net, val_dataset)
  File "train.py", line 734, in compute_validation_map
    eval_script.evaluate(yolact_net, dataset, train_mode=True, train_cfg=cfg)
  File "/content/radar/eval.py", line 1061, in evaluate
    preds = net(batch, extras=extras)["pred_outs"]
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/yolact_edge/yolact.py", line 1876, in forward
    outs_wrapper["pred_outs"] = self.detect(pred_outs, extras=extras)
  File "/content/yolact_edge/layers/functions/detection.py", line 74, in __call__
    conf_preds = conf_data.view(batch_size, num_priors, self.num_classes).transpose(2, 1).contiguous()
RuntimeError: shape '[1, 6958, 81]' is invalid for input of size 396900
```

I'm so close to getting things working but I always seem to hit a new bump in the road. Any help would be greatly appreciated!

**Comment by haotian-liu** [comment]
It seems that the backbone channel is not correctly defined in your case. You can take a look at how FPN is initialized [here](https://github.com/haotian-liu/yolact_edge/blob/master/yolact.py#L1124-L1130).

**Comment by cyrilzakka** [comment]
Hmmm I seem to have misunderstood what `self.channels` is supposed to be. In my backbone's `self.channels`, I'm just appending all of the input channels of the layers in the backbone. Is that incorrect? What exactly goes in `self.channels`? Is is just supposed to be the input channels of the layers I return in `forward(self, x)`

**Comment by haotian-liu** [comment]
It should be the channel number of all the tensors you return.

**Comment by cyrilzakka** [comment]
Okay one last question, are the tensors I return in `forward(self,x)`, the tensors I want to use for FPN, or is it any and all tensors that are then selected for FPN using `selected_layers`? Is there a downside to returning all tensors or the ones for FPN only? Or is that a design choice I make?

**Comment by haotian-liu** [comment]
If you are not sure what tensors you are going to use, then you might want to return all of them, and then select as it will be more flexible. And given that is only 30 layers, the selection won't take much time, so it should be okay for both (although I haven't experimented of returning 30 tensors, theoretically it shall be fine)

**Comment by cyrilzakka** [comment]
Alright thank you so much and sorry for the bother! I'll close this issue for now!

**Comment by cyrilzakka** [comment]
Okay so I fixed the channels, but I'm still getting this error:
```
[01/18 05:10:55 yolact.train]: eta: 0:00:00  epoch: 0  iter: 0  B: 8.548  M: 127.678  C: 21.162  S: 61.222  T: 218.611  time: 4.694  data_time: 0.000  lr: 0.000100  max_mem: 4410M
[01/18 05:10:59 yolact.eval]: Computing validation mAP (this may take a while)...

Traceback (most recent call last):
  File "train.py", line 746, in <module>
    train(0, args=args)
  File "train.py", line 642, in train
    compute_validation_map(yolact_net, val_dataset)
  File "train.py", line 734, in compute_validation_map
    eval_script.evaluate(yolact_net, dataset, train_mode=True, train_cfg=cfg)
  File "/content/yolact_edge/eval.py", line 1061, in evaluate
    preds = net(batch, extras=extras)["pred_outs"]
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/yolact_edge/yolact.py", line 1878, in forward
    outs_wrapper["pred_outs"] = self.detect(pred_outs, extras=extras)
  File "/content/yolact_edge/layers/functions/detection.py", line 74, in __call__
    conf_preds = conf_data.view(batch_size, num_priors, self.num_classes).transpose(2, 1).contiguous()
RuntimeError: shape '[1, 8036, 81]' is invalid for input of size 460404
```

There's this weird bug as well:
If I specify `selected_layers` to be [0,1,2] and then in `yolact.py` I print them like this:
```
for idx, layer_idx in enumerate(self.selected_layers):
            # If we're sharing prediction module weights, have every module's parent be the first one
            print(self.selected_layers)
            print(idx, layer_idx)
```

I get `[0,1,2,3,4]` instead. Any ideas?

**Comment by cyrilzakka** [comment]
Okay so I fixed the channels, but I'm still getting this error:
```
[01/18 05:10:55 yolact.train]: eta: 0:00:00  epoch: 0  iter: 0  B: 8.548  M: 127.678  C: 21.162  S: 61.222  T: 218.611  time: 4.694  data_time: 0.000  lr: 0.000100  max_mem: 4410M
[01/18 05:10:59 yolact.eval]: Computing validation mAP (this may take a while)...

Traceback (most recent call last):
  File "train.py", line 746, in <module>
    train(0, args=args)
  File "train.py", line 642, in train
    compute_validation_map(yolact_net, val_dataset)
  File "train.py", line 734, in compute_validation_map
    eval_script.evaluate(yolact_net, dataset, train_mode=True, train_cfg=cfg)
  File "/content/yolact_edge/eval.py", line 1061, in evaluate
    preds = net(batch, extras=extras)["pred_outs"]
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/yolact_edge/yolact.py", line 1878, in forward
    outs_wrapper["pred_outs"] = self.detect(pred_outs, extras=extras)
  File "/content/yolact_edge/layers/functions/detection.py", line 74, in __call__
    conf_preds = conf_data.view(batch_size, num_priors, self.num_classes).transpose(2, 1).contiguous()
RuntimeError: shape '[1, 8036, 81]' is invalid for input of size 460404
```

There's this weird bug as well:
If I specify `selected_layers` to be [0,1,2] and then in `yolact.py` I print them like this:
```
for idx, layer_idx in enumerate(self.selected_layers):
            # If we're sharing prediction module weights, have every module's parent be the first one
            print(self.selected_layers)
            print(idx, layer_idx)
```

I get `[0,1,2,3,4]` instead. Any ideas?

**Comment by cyrilzakka** [comment]
I changed the dataset to COCO and it seems to be training for now:
`[01/18 05:42:40 yolact.train]: eta: 4 days, 1:13:42  epoch: 1  iter: 1210  B: 6.810  M: 6.584  C: 6.515  S: 1.223  T: 21.132  time: 0.353  data_time: 0.013  lr: 0.001000  max_mem: 4509M`
Will wait until mAP is calculated before reporting back.

**Comment by haotian-liu** [comment]
This is expected as it includes downsample layers in FPN.

**Comment by cyrilzakka** [comment]
Makes sense! Any ideas about the error on the calculation of mAP? The network trains fine until mAP is calculated then it crashes:

```
[01/18 05:47:02 yolact.train]: eta: 4 days, 1:55:24  epoch: 2  iter: 1800  B: 6.712  M: 6.604  C: 6.308  S: 1.272  T: 20.896  time: 0.422  data_time: 0.019  lr: 0.001000  max_mem: 4509M
[01/18 05:47:06 yolact.train]: eta: 4 days, 1:52:10  epoch: 2  iter: 1810  B: 6.601  M: 6.644  C: 6.319  S: 1.267  T: 20.830  time: 0.518  data_time: 0.013  lr: 0.001000  max_mem: 4509M
[01/18 05:47:10 yolact.train]: eta: 4 days, 1:52:07  epoch: 2  iter: 1820  B: 6.624  M: 6.646  C: 6.303  S: 1.301  T: 20.874  time: 0.481  data_time: 0.014  lr: 0.001000  max_mem: 4509M
[01/18 05:47:15 yolact.train]: eta: 4 days, 1:47:49  epoch: 2  iter: 1830  B: 6.568  M: 6.597  C: 6.253  S: 1.336  T: 20.754  time: 0.389  data_time: 0.012  lr: 0.001000  max_mem: 4509M
[01/18 05:47:19 yolact.train]: eta: 4 days, 1:42:09  epoch: 2  iter: 1840  B: 6.465  M: 6.573  C: 6.221  S: 1.325  T: 20.584  time: 0.445  data_time: 0.015  lr: 0.001000  max_mem: 4509M
[01/18 05:47:23 yolact.train]: eta: 4 days, 1:48:38  epoch: 2  iter: 1850  B: 6.458  M: 6.536  C: 6.259  S: 1.307  T: 20.560  time: 0.515  data_time: 0.047  lr: 0.001000  max_mem: 4509M
[01/18 05:47:26 yolact.eval]: Computing validation mAP (this may take a while)...

Traceback (most recent call last):
  File "train.py", line 746, in <module>
    train(0, args=args)
  File "train.py", line 642, in train
    compute_validation_map(yolact_net, val_dataset)
  File "train.py", line 734, in compute_validation_map
    eval_script.evaluate(yolact_net, dataset, train_mode=True, train_cfg=cfg)
  File "/content/yolact_edge/eval.py", line 1061, in evaluate
    preds = net(batch, extras=extras)["pred_outs"]
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/yolact_edge/yolact.py", line 1876, in forward
    outs_wrapper["pred_outs"] = self.detect(pred_outs, extras=extras)
  File "/content/yolact_edge/layers/functions/detection.py", line 74, in __call__
    conf_preds = conf_data.view(batch_size, num_priors, self.num_classes).transpose(2, 1).contiguous()
RuntimeError: shape '[1, 4718, 81]' is invalid for input of size 339876
```

**Comment by haotian-liu** [comment]
@cyrilzakka You can verify the prediction outputs before it is concatenated and see if they match. See [here](https://github.com/haotian-liu/yolact_edge/blob/master/yolact.py#L260).

**Comment by cyrilzakka** [comment]
@haotian-liu would you mind explaining a bit more? What exactly should match? And why does this only happen when calculating mAP?

**Comment by haotian-liu** [comment]
@cyrilzakka According to the error message you posted, the conf_data does not match with the priors.
```
conf_preds = conf_data.view(batch_size, num_priors, self.num_classes).transpose(2, 1).contiguous()
RuntimeError: shape '[1, 4718, 81]' is invalid for input of size 339876
```
The final predictions are concatenated by the outputs of all prediction heads. Thus, we need to make sure that they match in each prediction heads. If they match, we might want to check in later stages.

Because when calculating mAP, the model will perform some steps that does not happen during training (e.g. NMS). Normally we do not see a difference between training and evaluation, but given you are modifying the backbones, configs, this could happen if some of them are not correctly modified.

**Comment by cyrilzakka** [comment]
In `detection.py` if I print the following:
```
with timer.env('Detect'):
            batch_size = loc_data.size(0)
            num_priors = prior_data.size(0)
            print(batch_size, num_priors, self.num_classes)
            print(conf_data.shape)
            conf_preds = conf_data.view(batch_size, num_priors, self.num_classes).transpose(2, 1).contiguous()
```

I get 
```
1 4718 81
torch.Size([1, 4196, 81])
```
So either `conf_data` or `num_priors` is the error source. Will continue investigating. Writing this as a partial summary to myself

**Comment by haotian-liu** [comment]
@cyrilzakka You should also check for priors here so that you can understand the problem better and locate the problem.

```python
for k, v in pred_outs.items():
            if k == 'conf':
                print(v[0].shape, v[1].shape, v[2].shape, v[3].shape, v[4].shape)
            pred_outs[k] = torch.cat(v, -2)
```

**Comment by cyrilzakka** [comment]
Priors: `torch.Size([8, 3136, 81]) torch.Size([8, 784, 81]) torch.Size([8, 196, 81]) torch.Size([8, 64, 81]) torch.Size([8, 16, 81]`)
Conf: `torch.Size([3136, 4]) torch.Size([1176, 4]) torch.Size([294, 4]) torch.Size([96, 4]) torch.Size([16, 4])`

Now I need to figure out where the problem is

**Comment by haotian-liu** [comment]
This is weird. What I noticed is that for row 2-4, the number of conf is 1.5x of that of priors. Maybe trace through the prediction heads and see what happens during the generation.

Btw, I just took a look again at the original post: your code starts to evaluate right after iteration zero? This is not normal..

**Comment by haotian-liu** [comment]
Another possible attempt: If you directly run the evaluation script, will you see the same error?

**Comment by cyrilzakka** [comment]
> This is weird. What I noticed is that for row 2-4, the number of conf is 1.5x of that of priors. Maybe trace through the prediction heads and see what happens during the generation.
> 
> Btw, I just took a look again at the original post: your code starts to evaluate right after iteration zero? This is not normal..

The reason the evaluation starts at 0 on my first post is because I downloaded a tiny COCO dataset on Colab so I wouldn't have to download all 21GB. On the normal COCO dataset, it trains normally until mAP is calculated. I'll check the prediction heads but I haven't changed anything else in the code. Just the backbone and the image size in config.py.

**Comment by cyrilzakka** [comment]
> Another possible attempt: If you directly run the evaluation script, will you see the same error?

I'll try this when I get home but when I tried to yesterday, I was getting errors relating to https://github.com/haotian-liu/yolact_edge/blob/4eb96ed0e2d58ed9fff21ebda1ac5c489b3f5e3b/eval.py#L11, where cfg, STD and MEAN couldn't be found and I had to fix imports. I just continued debugging my initial problem instead. I'll try to eval tonight and let you know!

**Comment by haotian-liu** [comment]
Btw what is the mini coco dataset you use on Colab (just curious).

**Comment by cyrilzakka** [comment]
> Btw what is the mini coco dataset you use on Colab (just curious).

Here you go! It's really tiny but it does the job in case you want to move quickly! https://github.com/dataloop-ai/tiny_coco

**Comment by cyrilzakka** [comment]
> Another possible attempt: If you directly run the evaluation script, will you see the same error?

```
Traceback (most recent call last):
  File "eval.py", line 1, in <module>
    from data import COCODetection, YoutubeVIS, get_label_map, MEANS, COLORS
  File "/content/yolact_edge/data/__init__.py", line 1, in <module>
    from .config import *
  File "/content/yolact_edge/data/config.py", line 1, in <module>
    from backbone import ResNetBackbone, VGGBackbone, ResNetBackboneGN, DarkNetBackbone, MobileNetV2Backbone, CNetBackbone
  File "/content/yolact_edge/backbone.py", line 15, in <module>
    from models.experimental import MixConv2d, CrossConv, C3
  File "/content/yolact_edge/models/experimental.py", line 8, in <module>
    from utils.google_utils import attempt_download
  File "/content/yolact_edge/utils/__init__.py", line 1, in <module>
    from .augmentations import SSDAugmentation
  File "/content/yolact_edge/utils/augmentations.py", line 8, in <module>
    from data import cfg, MEANS, STD
ImportError: cannot import name 'cfg'
```

**Comment by haotian-liu** [comment]
@cyrilzakka I had tried on Colab with newest code, and it worked fine. It seems that models.experimental tries to load utils.google_utils, and triggered utils.__init__.

**Comment by cyrilzakka** [comment]
Fixed the issue! As it turns out, I had some classes that were similarly named to the ones in this repository and that caused some (what should've been) forseeable circumstances!
