### ISSUE TITLE
Best way to train?

### ISSUE THREAD

**Issue by cyrilzakka** [haotian-liu/yolact_edge#35]
Hello again,

I have one final question. I have a backbone that does pretty well on the COCO dataset, getting around 48 APtest. What's the best way to train the model in order to get a good performance using Yolact Edge? Should I freeze the backbone and just have the FPN train? Any other insights?

**Comment by haotian-liu** [comment]
What do you mean that you have a backbone that has 48 AP on COCO, is it the backbone of a instance segmentor? You can start with loading the pretrained weights, freeze them, and fine tune the rest, and you might want to adjust the learning rate when needed.

**Comment by cyrilzakka** [comment]
Yes backbone of an instance segmentor. When training without freezing, the network trains normally. When freezing the backbone, 
```
[01/21 16:54:39 yolact.train]: eta: 3 days, 11:28:24  epoch: 0  iter: 350  B: 9.367  M: 7.460  C: 7.892  S: 1.326  T: 26.045  time: 0.248  data_time: 0.025  lr: 0.000730  max_mem: 2834M
[01/21 16:54:42 yolact.train]: eta: 3 days, 11:17:40  epoch: 0  iter: 360  B: 9.210  M: 7.305  C: 7.783  S: 1.301  T: 25.598  time: 0.282  data_time: 0.025  lr: 0.000748  max_mem: 2834M
[01/21 16:54:46 yolact.train]: eta: 3 days, 11:19:26  epoch: 0  iter: 370  B: 9.106  M: 7.132  C: 7.672  S: 1.294  T: 25.203  time: 0.316  data_time: 0.027  lr: 0.000766  max_mem: 2834M
[01/21 16:54:50 yolact.train]: eta: 3 days, 11:18:09  epoch: 0  iter: 380  B: 8.967  M: 7.076  C: 7.526  S: 1.301  T: 24.870  time: 0.285  data_time: 0.029  lr: 0.000784  max_mem: 2834M
[01/21 16:54:53 yolact.train]: eta: 3 days, 11:19:58  epoch: 0  iter: 390  B: 8.874  M: 7.050  C: 7.407  S: 1.291  T: 24.623  time: 0.342  data_time: 0.030  lr: 0.000802  max_mem: 2834M
[01/21 16:54:58 yolact.train]: eta: 3 days, 11:31:02  epoch: 0  iter: 400  B: 8.787  M: 7.222  C: 7.248  S: 1.332  T: 24.589  time: 0.509  data_time: 0.028  lr: 0.000820  max_mem: 2834M
[01/21 16:55:01 yolact.train]: eta: 3 days, 11:34:20  epoch: 0  iter: 410  B: 8.701  M: 7.186  C: 7.110  S: 1.408  T: 24.406  time: 0.349  data_time: 0.025  lr: 0.000838  max_mem: 2834M
[01/21 16:55:05 yolact.train]: eta: 3 days, 11:39:45  epoch: 0  iter: 420  B: 8.616  M: 7.209  C: 7.128  S: 1.434  T: 24.386  time: 0.485  data_time: 0.026  lr: 0.000856  max_mem: 2834M
[01/21 16:55:09 yolact.train]: eta: 3 days, 11:43:45  epoch: 0  iter: 430  B: 8.741  M: 20.276  C: 7.183  S: 1.416  T: 37.616  time: 0.424  data_time: 0.030  lr: 0.000874  max_mem: 2834M
[01/21 16:55:13 yolact.train]: eta: 3 days, 11:56:41  epoch: 0  iter: 440  B: 9.170  M: 196.520  C: 8.278  S: 1.419  T: 215.386  time: 0.439  data_time: 0.029  lr: 0.000892  max_mem: 2834M
[01/21 16:55:17 yolact.train]: eta: 3 days, 12:00:48  epoch: 0  iter: 450  B: 11.756  M: 314.264  C: 12.749  S: 1.604  T: 340.374  time: 0.407  data_time: 0.025  lr: 0.000910  max_mem: 2834M
[01/21 16:55:21 yolact.train]: eta: 3 days, 11:57:14  epoch: 0  iter: 460  B: 687.562  M: 381.424  C: 222.069  S: 2.562  T: 1293.617  time: 0.332  data_time: 0.025  lr: 0.000928  max_mem: 2834M
Warning: Moving average ignored a value of inf
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of inf
Warning: Moving average ignored a value of inf
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of inf
Warning: Moving average ignored a value of inf
Warning: Moving average ignored a value of nan
```

I guess M loss explodes. I'll investigate.

**Comment by haotian-liu** [comment]
If the backbone was from another instance segmentor, it might be better not to freeze it and start with that. If you want to try freezing the backbone, and see loss explodes, you could try with tuning the learning rates. If that keep pops up, then you might want to train everything without freezing.

**Comment by cyrilzakka** [comment]
I finally got everything working save for one thing. When training on a custom dataset, 
```
Traceback (most recent call last):
  File "train.py", line 746, in <module>
    train(0, args=args)
  File "train.py", line 642, in train
    compute_validation_map(yolact_net, val_dataset)
  File "train.py", line 734, in compute_validation_map
    eval_script.evaluate(yolact_net, dataset, train_mode=True, train_cfg=cfg)
  File "/content/radar/eval.py", line 1071, in evaluate
    prep_metrics(ap_data, preds, img, gt, gt_masks, h, w, num_crowd, dataset.ids[image_idx], detections)
  File "/content/radar/eval.py", line 458, in prep_metrics
    ap_obj = ap_data[iou_type][iouIdx][_class]
IndexError: list index out of range
```

it seems I need to set the number of classes somewhere that wasn't mentioned in the Readme. I have 11 classes. Any ideas?

**Comment by cyrilzakka** [comment]
Adding `'num_classes': len(custom_dataset.class_names) + 1,` seems to have fixed the issue for now!
