### ISSUE TITLE
Evaluate using TensorRT

### ISSUE THREAD

**Issue by minhhoangbui** [haotian-liu/yolact_edge#40]
Dear,
I use this command to evaluate this command to evaluate this model ```python eval.py --trained_model=./weights/yolact_edge_54_800000.pth --dataset=coco2017_dataset --use_fp16_tensorrt```
I encountered this error
```
Traceback (most recent call last):
  File "eval.py", line 1241, in <module>
    convert_to_tensorrt(net, cfg, args, transform=BaseTransform())
  File "/home/hoang/yolact_edge/utils/tensorrt.py", line 152, in convert_to_tensorrt
    net.to_tensorrt_backbone(cfg.torch2trt_backbone_int8, calibration_dataset=calibration_dataset, batch_size=args.trt_batch_size)
  File "/home/hoang/yolact_edge/yolact.py", line 1571, in to_tensorrt_backbone
    self.trt_load_if("backbone", trt_fn, [x], int8_mode, batch_size=batch_size)
  File "/home/hoang/yolact_edge/yolact.py", line 1554, in trt_load_if
    self.save_trt_cached_module(module, module_name, int8_mode, batch_size=batch_size)
  File "/home/hoang/yolact_edge/yolact.py", line 1545, in save_trt_cached_module
    torch.save(module.state_dict(), module_path)
  File "/home/hoang/miniconda3/envs/py3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 902, in state_dict
    hook_result = hook(self, destination, prefix, local_metadata)
  File "/home/hoang/miniconda3/envs/py3/lib/python3.7/site-packages/torch2trt-0.1.0-py3.7-linux-x86_64.egg/torch2trt/torch2trt.py", line 419, in _on_state_dict
    state_dict[prefix + "engine"] = bytearray(self.engine.serialize())
AttributeError: 'NoneType' object has no attribute 'serialize'
```
When I disable tensorrt option, everything is ok. Do you have any idea why it happens?
Thanks

**Comment by haotian-liu** [comment]
Have you compile the TensorRT correctly? It seems that self.engine for torch2trt is None?

**Comment by haotian-liu** [comment]
And when you install torch2trt, did you compile with `--plugins` option?

**Comment by minhhoangbui** [comment]
@haotian-liu Thank you for your support. My TensorRt is broken. I believe everyone should use docker to avoid these errors
