### ISSUE TITLE
ValueError: tuple.index(x): x not in tuple

### ISSUE THREAD

**Issue by yx868868** [haotian-liu/yolact_edge#50]
Hi,  I  really need your help. 
I train the project with yolact_edge_resnet50_config and my own coco style datasets on server ，but the error occured ：

Traceback (most recent call last):
  File "train.py", line 1, in <module>
    from utils import timer
  File "/home/yuxin/yolact_edge-master/utils/__init__.py", line 1, in <module>
    from .augmentations import SSDAugmentation
  File "/home/yuxin/yolact_edge-master/utils/augmentations.py", line 8, in <module>
    from data import cfg, MEANS, STD
  File "/home/yuxin/yolact_edge-master/data/__init__.py", line 1, in <module>
    from .config import *
  File "/home/yuxin/yolact_edge-master/data/config.py", line 89, in <module>
    COCO_YTVIS_LABEL_MAP = {COCO_INV_LABEL_MAP[COCO_CLASSES.index(coco) + 1]: YOUTUBE_VIS_CLASSES.index(ytvis) + 1 for coco, ytvis in COCO_YTVIS_CLASS_MAP.items()}
  File "/home/yuxin/yolact_edge-master/data/config.py", line 89, in <dictcomp>
    COCO_YTVIS_LABEL_MAP = {COCO_INV_LABEL_MAP[COCO_CLASSES.index(coco) + 1]: YOUTUBE_VIS_CLASSES.index(ytvis) + 1 for coco, ytvis in COCO_YTVIS_CLASS_MAP.items()}
ValueError: tuple.index(x): x not in tuple

have installed：
pytorch：1.6.0
Cython : 0.29.20
tensorrt ：7.1.3.4 
torch2trt : 0.1.0 
...
I  modify the config.py :

COCO_CLASSES, COCO_LABEL_MAP,images path, weights path and so on. 
But it does not work .
Looking forward to your reply .

**Comment by haotian-liu** [comment]
Hi, please create your own COCO_CLASSES (e.g. `CUSTOM_COCO_CLASSES`), and set it in `data/config.py` with `'class_names': CUSTOM_COCO_CLASSES`. Do the same thing for label maps, etc.

This error occurs because the COCO_YTVIS joint label map expects COCO_CLASSES as the input (but you modified it).
