### ISSUE TITLE
CUDA RuntimeError when cc_fast_nms is used instead of default fast_nms

### ISSUE THREAD

**Issue by ravijo** [haotian-liu/yolact_edge#53]
Hi,

Thank you for developing this amazing tool.

I noticed that `haotian-liu/yolact_edge` is using [fast_nms](https://github.com/haotian-liu/yolact_edge/blob/11840512ab46f22dce6aea37a7823110175adffa/layers/functions/detection.py#L102). However, `dbolya/yolact` provides [cc_fast_nms](https://github.com/dbolya/yolact/blob/57b8f2d95e62e2e649b382f516ab41f949b57239/layers/functions/detection.py#L99) too. Below is the modified `cc_fast_nms`
```
def cc_fast_nms(self, boxes, masks, scores, iou_threshold: float = 0.5, top_k: int = 200):
    scores, classes = scores.max(dim=0)

    _, idx = scores.sort(0, descending=True)
    idx = idx[:top_k]
    boxes_idx = torch.index_select(boxes, 0, idx)
    iou = jaccard(boxes_idx, boxes_idx)
    iou.triu_(diagonal=1)
    iou_max, _ = torch.max(iou, dim=0)

    idx_out = idx[iou_max <= iou_threshold].view(-1)
    boxes = torch.index_select(boxes, 0, idx_out)
    masks = torch.index_select(masks, 0, idx_out)
    classes = torch.index_select(classes, 0, idx_out)
    scores = torch.index_select(scores, 0, idx_out)     
    return boxes, masks, masks_secondary, classes, scores
```
You may notice `torch.index_select()` and `.view(-1)` in the above code. Sometimes the tensor `idx_out` was not in the correct shape so I flattened it using  `.view(-1)`. Well, while doing inference using TensorRT, the above code stops sometimes. The behavior is intermittent. The errors kept changing surprisingly. See below, please:

### Error 1
```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  # text removed
  File "/home/test/yolact_test/layers/output_utils.py", line 92, in postprocess
    masks = crop(masks, boxes)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/home/test/yolact_test/layers/box_utils.py", line 317, in fallback_function
    h, w, n = masks.size()
    x1, x2 = sanitize_coordinates(boxes[:, 0], boxes[:, 2], w, padding, cast=False)
    y1, y2 = sanitize_coordinates(boxes[:, 1], boxes[:, 3], h, padding, cast=False)
             ~~~~~~~~~~~~~~~~~~~~ <--- HERE

    rows = torch.arange(w, device=masks.device, dtype=x1.dtype).view(1, -1, 1).expand(h, w, n)
  File "/home/test/yolact_test/layers/box_utils.py", line 299, in sanitize_coordinates
    x1 = torch.min(_x1, _x2)
    x2 = torch.max(_x1, _x2)
    x1 = torch.clamp(x1-padding, min=0)
                     ~~~~~~~~~~ <--- HERE
    x2 = torch.clamp(x2+padding, max=img_size)
RuntimeError: CUDA error: device-side assert triggered
```

### Error 2
```
File "/home/test/yolact_test/layers/output_utils.py", line 92, in postprocess
  masks = crop(masks, boxes)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/home/test/yolact_test/layers/box_utils.py", line 316, in fallback_function
    """
    h, w, n = masks.size()
    x1, x2 = sanitize_coordinates(boxes[:, 0], boxes[:, 2], w, padding, cast=False)
             ~~~~~~~~~~~~~~~~~~~~ <--- HERE
    y1, y2 = sanitize_coordinates(boxes[:, 1], boxes[:, 3], h, padding, cast=False)
  File "/home/test/yolact_test/layers/box_utils.py", line 292, in sanitize_coordinates
    Warning: this does things in-place behind the scenes so copy if necessary.
    """
    _x1 = _x1 * img_size
          ~~~~~~~~~~~~~~ <--- HERE
    _x2 = _x2 * img_size
    if cast:
RuntimeError: CUDA error: device-side assert triggered
```

### Error 3
```
File "/home/test/yolact_test/layers/output_utils.py", line 92, in postprocess
  masks = crop(masks, boxes)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/home/test/yolact_test/layers/box_utils.py", line 317, in fallback_function
    x1, x2 = sanitize_coordinates(boxes[:, 0], boxes[:, 2], w, padding, cast=False)
    y1, y2 = sanitize_coordinates(boxes[:, 1], boxes[:, 3], h, padding, cast=False)
             ~~~~~~~~~~~~~~~~~~~~ <--- HERE

    rows = torch.arange(w, device=masks.device, dtype=x1.dtype).view(1, -1, 1).expand(h, w, n)
  File "/home/test/yolact_test/layers/box_utils.py", line 299, in sanitize_coordinates
    x2 = torch.max(_x1, _x2)
    x1 = torch.clamp(x1-padding, min=0)
    x2 = torch.clamp(x2+padding, max=img_size)
         ~~~~~~~~~~~ <--- HERE

    return x1, x2
RuntimeError: CUDA error: device-side assert triggered
```

### Error 4
```
File "/home/test/yolact_test/layers/output_utils.py", line 87, in postprocess
  masks = proto_data @ masks.t()
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
```

### Error 5
```
File "/home/test/yolact_test/layers/output_utils.py", line 88, in postprocess
  masks = cfg.mask_proto_mask_activation(masks)
RuntimeError: CUDA error: device-side assert triggered
```

As a workaround, I am setting the `use_fast_nms` to `false`.

**Comment by haotian-liu** [comment]
`cc_fast_nms` is not implemented in our main project. I pushed one implementation in 5719f2e, hope it helps.

**Comment by ravijo** [comment]
Thank you so much, @haotian-liu 

I just used your implementation and noticed the difference in `idx_out` [computation](https://github.com/haotian-liu/yolact_edge/blob/5719f2ec94327605742ab185e1634d39820d8154/layers/functions/detection.py#L161-L162). Unfortunately, now the code is throwing the following error:

```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/test/yolact_test/layers/output_utils.py", line 88, in postprocess
    masks = cfg.mask_proto_mask_activation(masks)
RuntimeError: CUDA error: device-side assert triggered
```
**Please note that the error is shown only when using a stream of images.** More precisely, I am using ROS to get images from my camera and using YOLACT on each image one by one (i.e., batch size is 1). If we just give one image, there is no such error. I think the error will come again if we use a video.

I added a `print` statement to check the dimension of each tensor in the following way:
```
idx_keep = torch.nonzero(iou_max <= iou_threshold, as_tuple=True)[0]
idx_out = torch.index_select(idx, 0, idx_keep)

print('idx_out', idx_out.size(), 'boxes', boxes.size(), 'masks', masks.size(), 'classes', classes.size(), 'scores', scores.size())

boxes = torch.index_select(boxes, 0, idx_out)
masks = torch.index_select(masks, 0, idx_out)
classes = torch.index_select(classes, 0, idx_out)
scores = torch.index_select(scores, 0, idx_out)     

return boxes, masks, classes, scores
```

Below is the output which shows that `idx_out` becomes of size 1 just before the error:
```
idx_out torch.Size([2]) boxes torch.Size([18, 4]) masks torch.Size([18, 32]) classes torch.Size([18]) scores torch.Size([18])
idx_out torch.Size([2]) boxes torch.Size([20, 4]) masks torch.Size([20, 32]) classes torch.Size([20]) scores torch.Size([20])
idx_out torch.Size([3]) boxes torch.Size([24, 4]) masks torch.Size([24, 32]) classes torch.Size([24]) scores torch.Size([24])
idx_out torch.Size([3]) boxes torch.Size([28, 4]) masks torch.Size([28, 32]) classes torch.Size([28]) scores torch.Size([28])
idx_out torch.Size([3]) boxes torch.Size([28, 4]) masks torch.Size([28, 32]) classes torch.Size([28]) scores torch.Size([28])
idx_out torch.Size([3]) boxes torch.Size([26, 4]) masks torch.Size([26, 32]) classes torch.Size([26]) scores torch.Size([26])
idx_out torch.Size([3]) boxes torch.Size([28, 4]) masks torch.Size([28, 32]) classes torch.Size([28]) scores torch.Size([28])
idx_out torch.Size([3]) boxes torch.Size([29, 4]) masks torch.Size([29, 32]) classes torch.Size([29]) scores torch.Size([29])
idx_out torch.Size([3]) boxes torch.Size([24, 4]) masks torch.Size([24, 32]) classes torch.Size([24]) scores torch.Size([24])
idx_out torch.Size([3]) boxes torch.Size([27, 4]) masks torch.Size([27, 32]) classes torch.Size([27]) scores torch.Size([27])
idx_out torch.Size([3]) boxes torch.Size([27, 4]) masks torch.Size([27, 32]) classes torch.Size([27]) scores torch.Size([27])
idx_out torch.Size([3]) boxes torch.Size([29, 4]) masks torch.Size([29, 32]) classes torch.Size([29]) scores torch.Size([29])
idx_out torch.Size([3]) boxes torch.Size([29, 4]) masks torch.Size([29, 32]) classes torch.Size([29]) scores torch.Size([29])
idx_out torch.Size([3]) boxes torch.Size([27, 4]) masks torch.Size([27, 32]) classes torch.Size([27]) scores torch.Size([27])
idx_out torch.Size([3]) boxes torch.Size([28, 4]) masks torch.Size([28, 32]) classes torch.Size([28]) scores torch.Size([28])
idx_out torch.Size([3]) boxes torch.Size([27, 4]) masks torch.Size([27, 32]) classes torch.Size([27]) scores torch.Size([27])
idx_out torch.Size([3]) boxes torch.Size([28, 4]) masks torch.Size([28, 32]) classes torch.Size([28]) scores torch.Size([28])
idx_out torch.Size([3]) boxes torch.Size([29, 4]) masks torch.Size([29, 32]) classes torch.Size([29]) scores torch.Size([29])
idx_out torch.Size([3]) boxes torch.Size([29, 4]) masks torch.Size([29, 32]) classes torch.Size([29]) scores torch.Size([29])
idx_out torch.Size([3]) boxes torch.Size([26, 4]) masks torch.Size([26, 32]) classes torch.Size([26]) scores torch.Size([26])
idx_out torch.Size([2]) boxes torch.Size([28, 4]) masks torch.Size([28, 32]) classes torch.Size([28]) scores torch.Size([28])
idx_out torch.Size([3]) boxes torch.Size([28, 4]) masks torch.Size([28, 32]) classes torch.Size([28]) scores torch.Size([28])
idx_out torch.Size([3]) boxes torch.Size([27, 4]) masks torch.Size([27, 32]) classes torch.Size([27]) scores torch.Size([27])
idx_out torch.Size([2]) boxes torch.Size([27, 4]) masks torch.Size([27, 32]) classes torch.Size([27]) scores torch.Size([27])
idx_out torch.Size([3]) boxes torch.Size([26, 4]) masks torch.Size([26, 32]) classes torch.Size([26]) scores torch.Size([26])
idx_out torch.Size([2]) boxes torch.Size([26, 4]) masks torch.Size([26, 32]) classes torch.Size([26]) scores torch.Size([26])
idx_out torch.Size([3]) boxes torch.Size([29, 4]) masks torch.Size([29, 32]) classes torch.Size([29]) scores torch.Size([29])
idx_out torch.Size([3]) boxes torch.Size([26, 4]) masks torch.Size([26, 32]) classes torch.Size([26]) scores torch.Size([26])
idx_out torch.Size([3]) boxes torch.Size([29, 4]) masks torch.Size([29, 32]) classes torch.Size([29]) scores torch.Size([29])
idx_out torch.Size([2]) boxes torch.Size([26, 4]) masks torch.Size([26, 32]) classes torch.Size([26]) scores torch.Size([26])
idx_out torch.Size([3]) boxes torch.Size([26, 4]) masks torch.Size([26, 32]) classes torch.Size([26]) scores torch.Size([26])
idx_out torch.Size([3]) boxes torch.Size([29, 4]) masks torch.Size([29, 32]) classes torch.Size([29]) scores torch.Size([29])
idx_out torch.Size([2]) boxes torch.Size([26, 4]) masks torch.Size([26, 32]) classes torch.Size([26]) scores torch.Size([26])
idx_out torch.Size([3]) boxes torch.Size([28, 4]) masks torch.Size([28, 32]) classes torch.Size([28]) scores torch.Size([28])
idx_out torch.Size([3]) boxes torch.Size([31, 4]) masks torch.Size([31, 32]) classes torch.Size([31]) scores torch.Size([31])
idx_out torch.Size([3]) boxes torch.Size([29, 4]) masks torch.Size([29, 32]) classes torch.Size([29]) scores torch.Size([29])
idx_out torch.Size([3]) boxes torch.Size([29, 4]) masks torch.Size([29, 32]) classes torch.Size([29]) scores torch.Size([29])
idx_out torch.Size([3]) boxes torch.Size([27, 4]) masks torch.Size([27, 32]) classes torch.Size([27]) scores torch.Size([27])
idx_out torch.Size([3]) boxes torch.Size([29, 4]) masks torch.Size([29, 32]) classes torch.Size([29]) scores torch.Size([29])
idx_out torch.Size([3]) boxes torch.Size([26, 4]) masks torch.Size([26, 32]) classes torch.Size([26]) scores torch.Size([26])
idx_out torch.Size([3]) boxes torch.Size([28, 4]) masks torch.Size([28, 32]) classes torch.Size([28]) scores torch.Size([28])
idx_out torch.Size([2]) boxes torch.Size([28, 4]) masks torch.Size([28, 32]) classes torch.Size([28]) scores torch.Size([28])
idx_out torch.Size([3]) boxes torch.Size([25, 4]) masks torch.Size([25, 32]) classes torch.Size([25]) scores torch.Size([25])
idx_out torch.Size([3]) boxes torch.Size([29, 4]) masks torch.Size([29, 32]) classes torch.Size([29]) scores torch.Size([29])
idx_out torch.Size([3]) boxes torch.Size([29, 4]) masks torch.Size([29, 32]) classes torch.Size([29]) scores torch.Size([29])
idx_out torch.Size([3]) boxes torch.Size([26, 4]) masks torch.Size([26, 32]) classes torch.Size([26]) scores torch.Size([26])
idx_out torch.Size([3]) boxes torch.Size([28, 4]) masks torch.Size([28, 32]) classes torch.Size([28]) scores torch.Size([28])
idx_out torch.Size([3]) boxes torch.Size([29, 4]) masks torch.Size([29, 32]) classes torch.Size([29]) scores torch.Size([29])
idx_out torch.Size([3]) boxes torch.Size([27, 4]) masks torch.Size([27, 32]) classes torch.Size([27]) scores torch.Size([27])
idx_out torch.Size([3]) boxes torch.Size([24, 4]) masks torch.Size([24, 32]) classes torch.Size([24]) scores torch.Size([24])
idx_out torch.Size([2]) boxes torch.Size([26, 4]) masks torch.Size([26, 32]) classes torch.Size([26]) scores torch.Size([26])
idx_out torch.Size([3]) boxes torch.Size([29, 4]) masks torch.Size([29, 32]) classes torch.Size([29]) scores torch.Size([29])
idx_out torch.Size([3]) boxes torch.Size([27, 4]) masks torch.Size([27, 32]) classes torch.Size([27]) scores torch.Size([27])
idx_out torch.Size([3]) boxes torch.Size([26, 4]) masks torch.Size([26, 32]) classes torch.Size([26]) scores torch.Size([26])
idx_out torch.Size([3]) boxes torch.Size([26, 4]) masks torch.Size([26, 32]) classes torch.Size([26]) scores torch.Size([26])
idx_out torch.Size([3]) boxes torch.Size([25, 4]) masks torch.Size([25, 32]) classes torch.Size([25]) scores torch.Size([25])
idx_out torch.Size([3]) boxes torch.Size([24, 4]) masks torch.Size([24, 32]) classes torch.Size([24]) scores torch.Size([24])
idx_out torch.Size([3]) boxes torch.Size([23, 4]) masks torch.Size([23, 32]) classes torch.Size([23]) scores torch.Size([23])
idx_out torch.Size([3]) boxes torch.Size([22, 4]) masks torch.Size([22, 32]) classes torch.Size([22]) scores torch.Size([22])
idx_out torch.Size([3]) boxes torch.Size([26, 4]) masks torch.Size([26, 32]) classes torch.Size([26]) scores torch.Size([26])
idx_out torch.Size([3]) boxes torch.Size([25, 4]) masks torch.Size([25, 32]) classes torch.Size([25]) scores torch.Size([25])
idx_out torch.Size([3]) boxes torch.Size([27, 4]) masks torch.Size([27, 32]) classes torch.Size([27]) scores torch.Size([27])
idx_out torch.Size([3]) boxes torch.Size([20, 4]) masks torch.Size([20, 32]) classes torch.Size([20]) scores torch.Size([20])
idx_out torch.Size([1]) boxes torch.Size([18, 4]) masks torch.Size([18, 32]) classes torch.Size([18]) scores torch.Size([18])

Exception in thread Thread-6:
Traceback (most recent call last):
```

**Comment by haotian-liu** [comment]
Please try this: use a try-except block to capture the error, and save the frame that caused the issue to the disk. Evaluate with image on that file and see if the problem persists.

**Comment by ravijo** [comment]
Thank you! I will report you back.

**Comment by ravijo** [comment]
The error is shown only when using `cc_fast_nms`. I added a few `print` statements and `try-except` blocks as shown below:

File [detection.py#L161-L162](https://github.com/haotian-liu/yolact_edge/blob/5719f2ec94327605742ab185e1634d39820d8154/layers/functions/detection.py#L161-L162)
```
idx_keep = torch.nonzero(iou_max <= iou_threshold, as_tuple=True)[0]
idx_out = torch.index_select(idx, 0, idx_keep)
print('detection.py L169 idx_out', idx_out.size(), 'boxes', boxes.size(), 'masks', masks.size(), 'classes', classes.size(), 'scores', scores.size())
try:
    boxes = torch.index_select(boxes, 0, idx_out)
    masks = torch.index_select(masks, 0, idx_out)
    classes = torch.index_select(classes, 0, idx_out)
    scores = torch.index_select(scores, 0, idx_out)
except Exception as e:
    print('detection.py L177', e)
return boxes, masks, classes, scores
```

File [output_utils.py#L39](https://github.com/haotian-liu/yolact_edge/blob/5719f2ec94327605742ab185e1634d39820d8154/layers/output_utils.py#L39)
```
print('output_utils.py L42 dets', dets.keys(), 'w', w, 'h', h, 'batch_idx', batch_idx, 'interpolation_mode', interpolation_mode, 'visualize_lincomb', visualize_lincomb, 'crop_masks', crop_masks, 'score_threshold', score_threshold)
for key in dets.keys():
    print('output_utils.py L44', key, dets[key].size())
```

File [output_utils.py#L87](https://github.com/haotian-liu/yolact_edge/blob/5719f2ec94327605742ab185e1634d39820d8154/layers/output_utils.py#L87)
```
try:
    print('output_utils.py L98 proto_data', proto_data.size(), 'masks', masks.size())
    masks = proto_data @ masks.t()
    masks = cfg.mask_proto_mask_activation(masks)
except Exception as e:
    print('output_utils.py L105', e)
```

### Output
The above `print` statements are giving the following information:
```
Converting PredictionModule to TensorRT...
Converted to TensorRT.
detection.py L169 idx_out torch.Size([1]) boxes torch.Size([18, 4]) masks torch.Size([18, 32]) classes torch.Size([18]) scores torch.Size([18])
output_utils.py L42 dets dict_keys(['box', 'mask', 'class', 'score', 'proto']) w 640 h 480 batch_idx 0 interpolation_mode bilinear visualize_lincomb False crop_masks True score_threshold 0.7
output_utils.py L44 box torch.Size([1, 4])
output_utils.py L44 mask torch.Size([1, 32])
output_utils.py L44 class torch.Size([1])
output_utils.py L44 score torch.Size([1])
output_utils.py L44 proto torch.Size([138, 138, 32])
output_utils.py L98 proto_data torch.Size([138, 138, 32]) masks torch.Size([1, 32])
/media/nvidia/WD_NVME/PyTorch/JetPack_4.4.1/pytorch-v1.7.0/aten/src/ATen/native/cuda/Indexing.cu:605: indexSelectSmallIndex: block: [0,0,0], thread: [0,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/media/nvidia/WD_NVME/PyTorch/JetPack_4.4.1/pytorch-v1.7.0/aten/src/ATen/native/cuda/Indexing.cu:605: indexSelectSmallIndex: block: [0,0,0], thread: [1,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/media/nvidia/WD_NVME/PyTorch/JetPack_4.4.1/pytorch-v1.7.0/aten/src/ATen/native/cuda/Indexing.cu:605: indexSelectSmallIndex: block: [0,0,0], thread: [2,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/media/nvidia/WD_NVME/PyTorch/JetPack_4.4.1/pytorch-v1.7.0/aten/src/ATen/native/cuda/Indexing.cu:605: indexSelectSmallIndex: block: [0,0,0], thread: [3,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
output_utils.py L105 CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`
Traceback (most recent call last):
  File "eval.py", line 1449, in <module>
    evaluate(net, dataset)
  File "eval.py", line 1062, in evaluate
    evalimage(net, args.image)
  File "eval.py", line 752, in evalimage
    img_numpy = prep_display(preds, frame, None, None, undo_transform=False)
  File "eval.py", line 182, in prep_display
    score_threshold=args.score_threshold)
  File "/home/test/yolact_test/layers/output_utils.py", line 114, in postprocess
    masks = crop(masks, boxes)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/home/test/yolact_test/layers/box_utils.py", line 317, in crop
    h, w, n = masks.size()
    x1, x2 = sanitize_coordinates(boxes[:, 0], boxes[:, 2], w, padding, cast=False)
    y1, y2 = sanitize_coordinates(boxes[:, 1], boxes[:, 3], h, padding, cast=False)
             ~~~~~~~~~~~~~~~~~~~~ <--- HERE

    rows = torch.arange(w, device=masks.device, dtype=x1.dtype).view(1, -1, 1).expand(h, w, n)
  File "/home/test/yolact_test/layers/box_utils.py", line 316, in sanitize_coordinates
    """
    h, w, n = masks.size()
    x1, x2 = sanitize_coordinates(boxes[:, 0], boxes[:, 2], w, padding, cast=False)
             ~~~~~~~~~~~~~~~~~~~~ <--- HERE
    y1, y2 = sanitize_coordinates(boxes[:, 1], boxes[:, 3], h, padding, cast=False)
RuntimeError: Expected 3 elements in a list but found 2
```

The error `CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)` is reported previously [here](https://github.com/haotian-liu/yolact_edge/issues/52#issuecomment-781232331) too. 

### Observation

I realized that the code works if `score_threshold` is set to 0. Any value higher than 0 raises the above error.

**Comment by haotian-liu** [comment]
I implemented a TensorRT safe mode (experimental) to securely handle those TensorRT related issues. Please try out `haotian-dev` branch, run the evaluation with `--use_tensorrt_safe_mode`, and see if it helps.

**Comment by ravijo** [comment]
Thank you so much, @haotian-liu 

I will report back if the issue persists.
