### ISSUE TITLE
Evaluate error on coco2017_testdev_dataset

### ISSUE THREAD

**Issue by tsangz189** [haotian-liu/yolact_edge#54]
Command: 
```
python eval.py --trained_model=./weights/yolact_edge_54_800000.pth --dataset=coco2017_testdev_dataset --disable_tensorrt
```
But generate error:
```
Config not specified. Parsed yolact_edge_config from the file name.

loading annotations into memory...
Done (t=0.04s)
creating index...
index created!
[02/18 20:28:39 yolact.eval]: Loading model...
[02/18 20:28:40 yolact.eval]: Model loaded.

Traceback (most recent call last):
  File "eval.py", line 1246, in <module>
    evaluate(net, dataset)
  File "eval.py", line 1048, in evaluate
    img, gt, gt_masks, h, w, num_crowd = dataset.pull_item(image_idx)
  File "/home/sangtr/dl/yolact_edge/data/coco.py", line 211, in pull_item
    if target.shape[0] == 0:
AttributeError: 'NoneType' object has no attribute 'shape'
```

But running without issues with validation split COCO. Any help is appreciated

**Comment by haotian-liu** [comment]
Fixed in 3aa5e39.
