### ISSUE TITLE
Error using traditional_nms

### ISSUE THREAD

**Issue by simutisernestas** [haotian-liu/yolact_edge#65]
Have you encountered this one? 

```
Traceback (most recent call last):
  File "test2.py", line 13, in <module>
    p = model_inference.predict(img, False)
  File "/home/ernestas/.local/lib/python3.8/site-packages/yolact_edge/inference.py", line 388, in predict
    preds = self.net(batch, extras=extras)["pred_outs"]
  File "/home/ernestas/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ernestas/.local/lib/python3.8/site-packages/yolact_edge/yolact.py", line 1798, in forward
    outs_wrapper["pred_outs"] = self.detect(pred_outs)
  File "/home/ernestas/.local/lib/python3.8/site-packages/yolact_edge/layers/functions/detection.py", line 75, in __call__
    result = self.detect(batch_idx, conf_preds, decoded_boxes, mask_data, inst_data)
  File "/home/ernestas/.local/lib/python3.8/site-packages/yolact_edge/layers/functions/detection.py", line 107, in detect
    boxes, masks, classes, scores = self.traditional_nms(boxes, masks, scores, self.nms_thresh, self.conf_thresh)
  File "/home/ernestas/.local/lib/python3.8/site-packages/yolact_edge/layers/functions/detection.py", line 260, in traditional_nms
    preds = torch.cat([boxes[conf_mask], cls_scores[:, None]], dim=1).cpu().numpy()
RuntimeError: Sizes of tensors must match except in dimension 2. Got 14 and 4 (The offending index is 0)
```

https://github.com/haotian-liu/yolact_edge/blob/6600d4675d10e67e5152095a763ba94863d6cf2b/layers/functions/detection.py#L34 changing this to True fixes the problem

**Comment by haotian-liu** [comment]
Because the cost of traditional NMS on the edge devices is not acceptable, thus the case for TensorRT errors is not handled with the traditional NMS.
