### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by VbsmRobotic** [haotian-liu/yolact_edge#79]
Hi
$ python3 train.py --config=yolact_edge_config  --batch_size=2 --num_gpus 1   --save_interval 1000

after few iterations, face the below error :

[03/27 10:20:28 yolact.train]: Args: train.py --config=yolact_edge_config --batch_size=2 --num_gpus 1 --save_interval 1000
[03/27 10:20:28 yolact.train]: git hash: 7e0bdbeba9e19232fa5b00622fbac1c26b17d5ef
loading annotations into memory...
Done (t=0.59s)
creating index...
index created!
loading annotations into memory...
Done (t=0.06s)
creating index...
index created!
[03/27 10:20:31 yolact.train]: Initializing weights...
[03/27 10:20:31 yolact.train]: Begin training!
/home/.../yolact_edge/utils/augmentations.py:414: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  mode = random.choice(self.sample_options)
/home/.../yolact_edge/utils/augmentations.py:414: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  mode = random.choice(self.sample_options)
/home/...../yolact_edge/utils/augmentations.py:414: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  mode = random.choice(self.sample_options)
/home/.../yolact_edge/utils/augmentations.py:414: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  mode = random.choice(self.sample_options)
[03/27 10:20:33 yolact.train]: eta: 0:00:00  epoch: 0  iter: 0  B: 8.010  M: 9.378  C: 20.959  S: 57.214  T: 95.561  time: 2.410  data_time: 0.000  lr: 0.000100  max_mem: 2257M
[03/27 10:20:37 yolact.train]: eta: 3 days, 6:39:03  epoch: 0  iter: 10  B: 6.736  M: 7.639  C: 18.209  S: 38.449  T: 71.034  time: 0.386  data_time: 0.009  lr: 0.000118  max_mem: 2667M
[03/27 10:20:41 yolact.train]: eta: 3 days, 10:37:37  epoch: 0  iter: 20  B: 7.419  M: 8.215  C: 15.921  S: 21.631  T: 53.185  time: 0.336  data_time: 0.019  lr: 0.000136  max_mem: 2721M
[03/27 10:20:45 yolact.train]: eta: 3 days, 16:20:27  epoch: 0  iter: 30  B: 7.240  M: 7.989  C: 14.565  S: 15.775  T: 45.568  time: 0.376  data_time: 0.094  lr: 0.000154  max_mem: 2721M
[03/27 10:20:49 yolact.train]: eta: 3 days, 15:23:33  epoch: 0  iter: 40  B: 7.095  M: 7.937  C: 12.573  S: 12.221  T: 39.826  time: 0.376  data_time: 0.023  lr: 0.000172  max_mem: 2721M
[03/27 10:20:53 yolact.train]: eta: 3 days, 15:06:46  epoch: 0  iter: 50  B: 6.867  M: 7.854  C: 10.975  S: 10.029  T: 35.725  time: 0.387  data_time: 0.023  lr: 0.000190  max_mem: 2721M
[03/27 10:20:57 yolact.train]: eta: 3 days, 14:36:53  epoch: 0  iter: 60  B: 6.667  M: 7.729  C: 10.193  S: 8.561  T: 33.150  time: 0.445  data_time: 0.015  lr: 0.000208  max_mem: 2725M
[03/27 10:21:01 yolact.train]: eta: 3 days, 14:30:37  epoch: 0  iter: 70  B: 6.805  M: 7.806  C: 9.678  S: 7.451  T: 31.740  time: 0.471  data_time: 0.028  lr: 0.000226  max_mem: 2729M
[03/27 10:21:05 yolact.train]: eta: 3 days, 15:17:36  epoch: 0  iter: 80  B: 6.760  M: 7.846  C: 9.041  S: 6.647  T: 30.295  time: 0.399  data_time: 0.051  lr: 0.000244  max_mem: 2729M
[03/27 10:21:08 yolact.train]: eta: 3 days, 14:40:01  epoch: 0  iter: 90  B: 6.813  M: 7.837  C: 8.600  S: 6.018  T: 29.267  time: 0.387  data_time: 0.014  lr: 0.000262  max_mem: 2729M
[03/27 10:21:12 yolact.train]: eta: 3 days, 14:50:03  epoch: 0  iter: 100  B: 6.675  M: 7.707  C: 8.041  S: 4.997  T: 27.419  time: 0.366  data_time: 0.041  lr: 0.000280  max_mem: 2729M
[03/27 10:21:16 yolact.train]: eta: 3 days, 14:06:16  epoch: 0  iter: 110  B: 6.547  M: 7.597  C: 6.624  S: 1.426  T: 22.195  time: 0.352  data_time: 0.010  lr: 0.000298  max_mem: 2729M
[03/27 10:21:19 yolact.train]: eta: 3 days, 13:30:57  epoch: 0  iter: 120  B: 6.374  M: 7.482  C: 5.721  S: 1.166  T: 20.743  time: 0.367  data_time: 0.013  lr: 0.000316  max_mem: 2729M
[03/27 10:21:24 yolact.train]: eta: 3 days, 13:57:52  epoch: 0  iter: 130  B: 6.293  M: 7.452  C: 4.964  S: 0.893  T: 19.603  time: 0.375  data_time: 0.039  lr: 0.000334  max_mem: 2729M
[03/27 10:21:27 yolact.train]: eta: 3 days, 13:33:34  epoch: 0  iter: 140  B: 6.303  M: 7.436  C: 4.775  S: 0.845  T: 19.360  time: 0.392  data_time: 0.011  lr: 0.000352  max_mem: 2729M
[03/27 10:21:31 yolact.train]: eta: 3 days, 13:18:15  epoch: 0  iter: 150  B: 6.395  M: 7.451  C: 4.773  S: 0.825  T: 19.444  time: 0.378  data_time: 0.014  lr: 0.000370  max_mem: 2729M
[03/27 10:21:35 yolact.train]: eta: 3 days, 13:36:10  epoch: 0  iter: 160  B: 6.510  M: 7.485  C: 4.609  S: 0.778  T: 19.382  time: 0.335  data_time: 0.041  lr: 0.000388  max_mem: 2729M
[03/27 10:21:39 yolact.train]: eta: 3 days, 14:18:01  epoch: 0  iter: 170  B: 6.415  M: 7.461  C: 4.370  S: 0.767  T: 19.013  time: 0.389  data_time: 0.077  lr: 0.000406  max_mem: 2729M
[03/27 10:21:43 yolact.train]: eta: 3 days, 14:17:52  epoch: 0  iter: 180  B: 6.594  M: 7.546  C: 4.430  S: 0.747  T: 19.317  time: 0.401  data_time: 0.016  lr: 0.000424  max_mem: 2729M
[03/27 10:21:48 yolact.train]: eta: 3 days, 15:42:08  epoch: 0  iter: 190  B: 6.548  M: 7.533  C: 4.434  S: 0.769  T: 19.284  time: 0.401  data_time: 0.150  lr: 0.000442  max_mem: 2729M
[03/27 10:21:52 yolact.train]: eta: 3 days, 15:31:36  epoch: 0  iter: 200  B: 6.590  M: 7.557  C: 4.460  S: 0.758  T: 19.365  time: 0.422  data_time: 0.017  lr: 0.000460  max_mem: 2729M
[03/27 10:21:56 yolact.train]: eta: 3 days, 15:20:11  epoch: 0  iter: 210  B: 6.670  M: 7.666  C: 4.458  S: 0.726  T: 19.520  time: 0.343  data_time: 0.015  lr: 0.000478  max_mem: 2729M
[03/27 10:22:00 yolact.train]: eta: 3 days, 15:09:07  epoch: 0  iter: 220  B: 6.739  M: 7.674  C: 4.412  S: 0.714  T: 19.539  time: 0.355  data_time: 0.015  lr: 0.000496  max_mem: 2729M
[03/27 10:22:03 yolact.train]: eta: 3 days, 14:54:59  epoch: 0  iter: 230  B: 6.817  M: 7.714  C: 4.430  S: 0.686  T: 19.647  time: 0.338  data_time: 0.013  lr: 0.000514  max_mem: 2729M
[03/27 10:22:07 yolact.train]: eta: 3 days, 14:38:20  epoch: 0  iter: 240  B: 6.889  M: 7.870  C: 4.517  S: 0.702  T: 19.978  time: 0.328  data_time: 0.012  lr: 0.000532  max_mem: 2729M
[03/27 10:22:10 yolact.train]: eta: 3 days, 14:22:09  epoch: 0  iter: 250  B: 6.841  M: 7.772  C: 4.596  S: 0.748  T: 19.958  time: 0.426  data_time: 0.015  lr: 0.000550  max_mem: 2729M
[03/27 10:22:14 yolact.train]: eta: 3 days, 14:03:00  epoch: 0  iter: 260  B: 6.967  M: 7.746  C: 4.645  S: 0.785  T: 20.141  time: 0.377  data_time: 0.009  lr: 0.000568  max_mem: 2729M
[03/27 10:22:18 yolact.train]: eta: 3 days, 13:52:53  epoch: 0  iter: 270  B: 7.127  M: 7.718  C: 4.794  S: 0.836  T: 20.475  time: 0.338  data_time: 0.013  lr: 0.000586  max_mem: 2729M
[03/27 10:22:21 yolact.train]: eta: 3 days, 13:38:37  epoch: 0  iter: 280  B: 6.994  M: 7.751  C: 5.032  S: 0.913  T: 20.690  time: 0.329  data_time: 0.012  lr: 0.000604  max_mem: 2729M
[03/27 10:22:25 yolact.train]: eta: 3 days, 13:28:49  epoch: 0  iter: 290  B: 6.947  M: 7.688  C: 5.270  S: 1.039  T: 20.944  time: 0.437  data_time: 0.013  lr: 0.000622  max_mem: 2729M
[03/27 10:22:29 yolact.train]: eta: 3 days, 13:21:21  epoch: 0  iter: 300  B: 7.285  M: 9.064  C: 5.575  S: 1.284  T: 23.209  time: 0.420  data_time: 0.019  lr: 0.000640  max_mem: 2729M
[03/27 10:22:32 yolact.train]: eta: 3 days, 13:17:49  epoch: 0  iter: 310  B: 7.429  M: 9.444  C: 6.488  S: 1.859  T: 25.220  time: 0.416  data_time: 0.014  lr: 0.000658  max_mem: 2729M
[03/27 10:22:36 yolact.train]: eta: 3 days, 13:13:15  epoch: 0  iter: 320  B: 7.564  M: 9.755  C: 7.921  S: 2.778  T: 28.018  time: 0.346  data_time: 0.015  lr: 0.000676  max_mem: 2729M
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [93,0,0], thread: [32,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [93,0,0], thread: [33,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [93,0,0], thread: [34,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [93,0,0], thread: [35,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [93,0,0], thread: [36,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [93,0,0], thread: [37,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [93,0,0], thread: [38,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [93,0,0], thread: [39,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [93,0,0], thread: [40,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [93,0,0], thread: [41,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [93,0,0], thread: [42,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [93,0,0], thread: [43,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [93,0,0], thread: [44,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [93,0,0], thread: [45,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [93,0,0], thread: [46,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [93,0,0], thread: [47,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [93,0,0], thread: [48,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [93,0,0], thread: [49,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [93,0,0], thread: [50,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [93,0,0], thread: [51,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [93,0,0], thread: [52,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [93,0,0], thread: [53,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [93,0,0], thread: [54,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [93,0,0], thread: [55,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [93,0,0], thread: [56,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [93,0,0], thread: [57,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [93,0,0], thread: [58,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [93,0,0], thread: [59,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [93,0,0], thread: [60,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [93,0,0], thread: [61,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [93,0,0], thread: [62,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [93,0,0], thread: [63,0,0] Assertion `input_val >= zero && input_val <= one` failed.
Traceback (most recent call last):
  File "train.py", line 707, in <module>
    train(0, args=args)
  File "train.py", line 433, in train
    losses = backward_and_log(run_name, net_outs, targets, masks, num_crowds)
  File "train.py", line 325, in backward_and_log
    losses = criterion(out, targets, masks, num_crowds)
  File "/home/.../python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/.../yolact_edge/layers/modules/multibox_loss.py", line 159, in forward
    losses.update(self.lincomb_mask_loss(pos, idx_t, loc_data, mask_data, priors, proto_data, masks, gt_box_t, inst_data))
  File "/home/.../yolact_edge/layers/modules/multibox_loss.py", line 470, in lincomb_mask_loss
    pos_idx_t = idx_t[idx, cur_pos]
RuntimeError: CUDA error: device-side assert triggered

Could you please advise?

**Comment by haotian-liu** [comment]
Your batch size is too small, please: (1) set `cfg.freeze_bn = True`; (2) set learning rate to 1/4 of the original.
