### ISSUE TITLE
Training Error

### ISSUE THREAD

**Issue by winter2897** [haotian-liu/yolact_edge#80]
# Error: RuntimeError: DataLoader worker (pid(s) 9570) exited unexpectedly

Hi @haotian-liu, 

I train YOLACT EDGE with customizable datasets. However, I encountered the error training suddenly killed.

I tried to follow your advice for issues #73 but not work. Can you give me some advice?  

## Data config

```
RTR_geo_dataset = dataset_base.copy({
    'name': 'RTR geo',
    
    'train_images': './data/geo/images/',
    'train_info': './data/geo/train.json',
    
    'valid_images': './data/geo/images/',
    'valid_info': './data/geo/test.json',
    

    'class_names': ('cable', 'tower_wooden', 'tower_lattice', 'tower_tucohy'),
    'label_map': {1:1, 2:2, 3:3, 4:4}
})
```

## Training Command
```
python train.py --batch_size=2 --num_workers=0  --config=yolact_edge_config --dataset=RTR_geo_dataset --resume=weights/yolact_edge_54_800000.pth
```
## Full Logs
Logs with different `number_worker` and` batch_size` parameters.
```
[03/30 14:56:38] yolact.train INFO: Args: train.py --config=yolact_edge_config --dataset=RTR_geo_dataset --resume=weights/yolact_edge_54_800000.pth
[03/30 14:56:38] yolact.train INFO: git hash: 16dd820a4bb8bacd24d1e2d05fea5b6b20ccde19
[03/30 14:56:41] yolact.train INFO: Resuming training, loading weights/yolact_edge_54_800000.pth...
[03/30 14:56:41] yolact.model.load WARNING: Some parameters in the checkpoint have a different shape in the current model, and are initialized as they should be: prediction_layers.0.conf_layer.weight, prediction_layers.0.conf_layer.bias, semantic_seg_conv.weight, semantic_seg_conv.bias
[03/30 14:56:41] yolact.train INFO: Begin training!
[03/30 14:56:55] yolact.train INFO: eta: 0:00:00  epoch: 0  iter: 0  B: 8.468  M: 3.835  C: 10.427  S: 3.683  T: 26.414  time: 13.673  data_time: 0.000  lr: 0.000100  max_mem: 7811M
[03/30 14:59:29] yolact.train INFO: Args: train.py --config=yolact_edge_config --dataset=RTR_geo_dataset --resume=weights/yolact_edge_54_800000.pth
[03/30 14:59:29] yolact.train INFO: git hash: 16dd820a4bb8bacd24d1e2d05fea5b6b20ccde19
[03/30 14:59:31] yolact.train INFO: Resuming training, loading weights/yolact_edge_54_800000.pth...
[03/30 14:59:32] yolact.model.load WARNING: Some parameters in the checkpoint have a different shape in the current model, and are initialized as they should be: prediction_layers.0.conf_layer.weight, prediction_layers.0.conf_layer.bias, semantic_seg_conv.weight, semantic_seg_conv.bias
[03/30 14:59:32] yolact.train INFO: Begin training!
[03/30 14:59:41] yolact.train INFO: eta: 0:00:00  epoch: 0  iter: 0  B: 8.468  M: 3.835  C: 10.427  S: 3.683  T: 26.414  time: 9.194  data_time: 0.000  lr: 0.000100  max_mem: 7811M
[03/30 15:00:47] yolact.train INFO: eta: 61 days, 9:40:05  epoch: 0  iter: 10  B: 10.183  M: 3.017  C: 7.508  S: 3.019  T: 23.727  time: 9.714  data_time: 5.779  lr: 0.000118  max_mem: 8157M
[03/30 15:01:47] yolact.train INFO: eta: 58 days, 7:01:03  epoch: 0  iter: 20  B: 9.317  M: 2.525  C: 6.374  S: 2.192  T: 20.408  time: 6.431  data_time: 5.102  lr: 0.000136  max_mem: 8218M
[03/30 15:05:31] yolact.train INFO: Args: train.py --batch_size=4 --num_workers=2 --config=yolact_edge_config --dataset=RTR_geo_dataset --resume=weights/yolact_edge_54_800000.pth
[03/30 15:05:31] yolact.train INFO: git hash: 16dd820a4bb8bacd24d1e2d05fea5b6b20ccde19
[03/30 15:05:34] yolact.train INFO: Resuming training, loading weights/yolact_edge_54_800000.pth...
[03/30 15:05:34] yolact.model.load WARNING: Some parameters in the checkpoint have a different shape in the current model, and are initialized as they should be: prediction_layers.0.conf_layer.weight, prediction_layers.0.conf_layer.bias, semantic_seg_conv.weight, semantic_seg_conv.bias
[03/30 15:05:34] yolact.train INFO: Begin training!
[03/30 15:05:40] yolact.train INFO: eta: 0:00:00  epoch: 0  iter: 0  B: 7.419  M: 3.795  C: 12.318  S: 3.657  T: 27.189  time: 5.468  data_time: 0.000  lr: 0.000100  max_mem: 4086M
[03/30 15:06:04] yolact.train INFO: Args: train.py --batch_size=4 --num_workers=1 --config=yolact_edge_config --dataset=RTR_geo_dataset --resume=weights/yolact_edge_54_800000.pth
[03/30 15:06:04] yolact.train INFO: git hash: 16dd820a4bb8bacd24d1e2d05fea5b6b20ccde19
[03/30 15:06:07] yolact.train INFO: Resuming training, loading weights/yolact_edge_54_800000.pth...
[03/30 15:06:07] yolact.model.load WARNING: Some parameters in the checkpoint have a different shape in the current model, and are initialized as they should be: prediction_layers.0.conf_layer.weight, prediction_layers.0.conf_layer.bias, semantic_seg_conv.weight, semantic_seg_conv.bias
[03/30 15:06:07] yolact.train INFO: Begin training!
[03/30 15:06:12] yolact.train INFO: eta: 0:00:00  epoch: 0  iter: 0  B: 7.419  M: 3.795  C: 12.318  S: 3.657  T: 27.189  time: 4.915  data_time: 0.000  lr: 0.000100  max_mem: 4086M
[03/30 15:06:45] yolact.train INFO: eta: 30 days, 15:46:07  epoch: 0  iter: 10  B: 10.986  M: 2.707  C: 7.669  S: 3.014  T: 24.376  time: 3.583  data_time: 2.863  lr: 0.000118  max_mem: 4437M
[03/30 15:07:17] yolact.train INFO: eta: 30 days, 4:50:09  epoch: 0  iter: 20  B: 10.610  M: 2.648  C: 6.487  S: 2.188  T: 21.933  time: 4.094  data_time: 2.768  lr: 0.000136  max_mem: 4437M
[03/30 15:07:53] yolact.train INFO: eta: 31 days, 6:48:41  epoch: 0  iter: 30  B: 10.830  M: 2.412  C: 5.671  S: 1.654  T: 20.567  time: 3.786  data_time: 3.159  lr: 0.000154  max_mem: 4477M
[03/30 15:08:23] yolact.train INFO: eta: 30 days, 7:19:14  epoch: 0  iter: 40  B: 9.758  M: 2.257  C: 5.146  S: 1.342  T: 18.503  time: 3.089  data_time: 2.507  lr: 0.000172  max_mem: 4477M
[03/30 15:09:43] yolact.train INFO: Args: train.py --batch_size=2 --num_workers=0 --config=yolact_edge_config --dataset=RTR_geo_dataset --resume=weights/yolact_edge_54_800000.pth
[03/30 15:09:43] yolact.train INFO: git hash: 16dd820a4bb8bacd24d1e2d05fea5b6b20ccde19
[03/30 15:09:46] yolact.train INFO: Resuming training, loading weights/yolact_edge_54_800000.pth...
[03/30 15:09:46] yolact.model.load WARNING: Some parameters in the checkpoint have a different shape in the current model, and are initialized as they should be: prediction_layers.0.conf_layer.weight, prediction_layers.0.conf_layer.bias, semantic_seg_conv.weight, semantic_seg_conv.bias
[03/30 15:09:47] yolact.train INFO: Begin training!
[03/30 15:09:50] yolact.train INFO: eta: 0:00:00  epoch: 0  iter: 0  B: 4.660  M: 3.677  C: 11.503  S: 3.708  T: 23.548  time: 3.420  data_time: 0.000  lr: 0.000100  max_mem: 2169M
[03/30 15:10:07] yolact.train INFO: eta: 15 days, 21:51:43  epoch: 0  iter: 10  B: 13.357  M: 2.970  C: 7.968  S: 3.047  T: 27.343  time: 1.127  data_time: 1.480  lr: 0.000118  max_mem: 2514M
[03/30 15:10:28] yolact.train INFO: eta: 17 days, 11:42:19  epoch: 0  iter: 20  B: 12.882  M: 2.505  C: 6.625  S: 2.222  T: 24.235  time: 2.458  data_time: 1.820  lr: 0.000136  max_mem: 2518M
[03/30 15:10:46] yolact.train INFO: eta: 17 days, 7:30:18  epoch: 0  iter: 30  B: 11.720  M: 2.215  C: 5.794  S: 1.697  T: 21.426  time: 2.617  data_time: 1.594  lr: 0.000154  max_mem: 2520M
[03/30 15:11:04] yolact.train INFO: eta: 17 days, 2:45:01  epoch: 0  iter: 40  B: 10.986  M: 2.368  C: 5.330  S: 1.377  T: 20.061  time: 3.043  data_time: 1.545  lr: 0.000172  max_mem: 2520M
[03/30 15:11:23] yolact.train INFO: eta: 17 days, 5:07:14  epoch: 0  iter: 50  B: 10.702  M: 2.312  C: 4.936  S: 1.157  T: 19.107  time: 0.745  data_time: 1.662  lr: 0.000190  max_mem: 2551M
[03/30 15:11:42] yolact.train INFO: eta: 17 days, 6:14:28  epoch: 0  iter: 60  B: 11.522  M: 2.346  C: 4.635  S: 1.002  T: 19.506  time: 1.642  data_time: 1.648  lr: 0.000208  max_mem: 2551M
[03/30 15:11:59] yolact.train INFO: eta: 17 days, 1:09:49  epoch: 0  iter: 70  B: 10.773  M: 2.336  C: 4.456  S: 0.905  T: 18.470  time: 1.256  data_time: 1.459  lr: 0.000226  max_mem: 2551M
[03/30 15:12:16] yolact.train INFO: eta: 16 days, 20:59:06  epoch: 0  iter: 80  B: 10.632  M: 2.320  C: 4.301  S: 0.827  T: 18.081  time: 1.636  data_time: 1.447  lr: 0.000244  max_mem: 2551M
[03/30 15:12:33] yolact.train INFO: eta: 16 days, 17:38:23  epoch: 0  iter: 90  B: 10.436  M: 2.236  C: 4.156  S: 0.763  T: 17.591  time: 3.349  data_time: 1.447  lr: 0.000262  max_mem: 2551M
```

## Error
1. `--batch_size=4 --num_workers=1`

```
[03/30 15:06:07 yolact.train]: Resuming training, loading weights/yolact_edge_54_800000.pth...
WARNING [03/30 15:06:07 yolact.model.load]: Some parameters in the checkpoint have a different shape in the current model, and are initialized as they should be: prediction_layers.0.conf_layer.weight, prediction_layers.0.conf_layer.bias, semantic_seg_conv.weight, semantic_seg_conv.bias
[03/30 15:06:07 yolact.train]: Begin training!
/home/quanrtr/yolact_edge/utils/augmentations.py:414: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  mode = random.choice(self.sample_options)
[03/30 15:06:12 yolact.train]: eta: 0:00:00  epoch: 0  iter: 0  B: 7.419  M: 3.795  C: 12.318  S: 3.657  T: 27.189  time: 4.915  data_time: 0.000  lr: 0.000100  max_mem: 4086M
[03/30 15:06:45 yolact.train]: eta: 30 days, 15:46:07  epoch: 0  iter: 10  B: 10.986  M: 2.707  C: 7.669  S: 3.014  T: 24.376  time: 3.583  data_time: 2.863  lr: 0.000118  max_mem: 4437M
[03/30 15:07:17 yolact.train]: eta: 30 days, 4:50:09  epoch: 0  iter: 20  B: 10.610  M: 2.648  C: 6.487  S: 2.188  T: 21.933  time: 4.094  data_time: 2.768  lr: 0.000136  max_mem: 4437M
[03/30 15:07:53 yolact.train]: eta: 31 days, 6:48:41  epoch: 0  iter: 30  B: 10.830  M: 2.412  C: 5.671  S: 1.654  T: 20.567  time: 3.786  data_time: 3.159  lr: 0.000154  max_mem: 4477M
[03/30 15:08:23 yolact.train]: eta: 30 days, 7:19:14  epoch: 0  iter: 40  B: 9.758  M: 2.257  C: 5.146  S: 1.342  T: 18.503  time: 3.089  data_time: 2.507  lr: 0.000172  max_mem: 4477M
Traceback (most recent call last):
  File "/home/quanrtr/miniconda3/envs/kun/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 872, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/quanrtr/miniconda3/envs/kun/lib/python3.6/multiprocessing/queues.py", line 104, in get
    if not self._poll(timeout):
  File "/home/quanrtr/miniconda3/envs/kun/lib/python3.6/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/home/quanrtr/miniconda3/envs/kun/lib/python3.6/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/home/quanrtr/miniconda3/envs/kun/lib/python3.6/multiprocessing/connection.py", line 911, in wait
    ready = selector.select(timeout)
  File "/home/quanrtr/miniconda3/envs/kun/lib/python3.6/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)
  File "/home/quanrtr/miniconda3/envs/kun/lib/python3.6/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 9570) is killed by signal: Killed. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 707, in <module>
    train(0, args=args)
  File "train.py", line 357, in train
    datum = next(data_loader_iter)
  File "/home/quanrtr/miniconda3/envs/kun/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/quanrtr/miniconda3/envs/kun/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1068, in _next_data
    idx, data = self._get_data()
  File "/home/quanrtr/miniconda3/envs/kun/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1034, in _get_data
    success, data = self._try_get_data()
  File "/home/quanrtr/miniconda3/envs/kun/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 885, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 9570) exited unexpectedly
```

2. `--batch_size=2 --num_workers=0`

```
[03/30 15:09:43 yolact.train]: Args: train.py --batch_size=2 --num_workers=0 --config=yolact_edge_config --dataset=RTR_geo_dataset --resume=weights/yolact_edge_54_800000.pth
[03/30 15:09:43 yolact.train]: git hash: 16dd820a4bb8bacd24d1e2d05fea5b6b20ccde19
loading annotations into memory...
Done (t=0.10s)
creating index...
index created!
loading annotations into memory...
Done (t=0.03s)
creating index...
index created!
[03/30 15:09:46 yolact.train]: Resuming training, loading weights/yolact_edge_54_800000.pth...
WARNING [03/30 15:09:46 yolact.model.load]: Some parameters in the checkpoint have a different shape in the current model, and are initialized as they should be: prediction_layers.0.conf_layer.weight, prediction_layers.0.conf_layer.bias, semantic_seg_conv.weight, semantic_seg_conv.bias
[03/30 15:09:47 yolact.train]: Begin training!
/home/quanrtr/yolact_edge/utils/augmentations.py:414: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  mode = random.choice(self.sample_options)
[03/30 15:09:50 yolact.train]: eta: 0:00:00  epoch: 0  iter: 0  B: 4.660  M: 3.677  C: 11.503  S: 3.708  T: 23.548  time: 3.420  data_time: 0.000  lr: 0.000100  max_mem: 2169M
[03/30 15:10:07 yolact.train]: eta: 15 days, 21:51:43  epoch: 0  iter: 10  B: 13.357  M: 2.970  C: 7.968  S: 3.047  T: 27.343  time: 1.127  data_time: 1.480  lr: 0.000118  max_mem: 2514M
[03/30 15:10:28 yolact.train]: eta: 17 days, 11:42:19  epoch: 0  iter: 20  B: 12.882  M: 2.505  C: 6.625  S: 2.222  T: 24.235  time: 2.458  data_time: 1.820  lr: 0.000136  max_mem: 2518M
[03/30 15:10:46 yolact.train]: eta: 17 days, 7:30:18  epoch: 0  iter: 30  B: 11.720  M: 2.215  C: 5.794  S: 1.697  T: 21.426  time: 2.617  data_time: 1.594  lr: 0.000154  max_mem: 2520M
[03/30 15:11:04 yolact.train]: eta: 17 days, 2:45:01  epoch: 0  iter: 40  B: 10.986  M: 2.368  C: 5.330  S: 1.377  T: 20.061  time: 3.043  data_time: 1.545  lr: 0.000172  max_mem: 2520M
[03/30 15:11:23 yolact.train]: eta: 17 days, 5:07:14  epoch: 0  iter: 50  B: 10.702  M: 2.312  C: 4.936  S: 1.157  T: 19.107  time: 0.745  data_time: 1.662  lr: 0.000190  max_mem: 2551M
[03/30 15:11:42 yolact.train]: eta: 17 days, 6:14:28  epoch: 0  iter: 60  B: 11.522  M: 2.346  C: 4.635  S: 1.002  T: 19.506  time: 1.642  data_time: 1.648  lr: 0.000208  max_mem: 2551M
[03/30 15:11:59 yolact.train]: eta: 17 days, 1:09:49  epoch: 0  iter: 70  B: 10.773  M: 2.336  C: 4.456  S: 0.905  T: 18.470  time: 1.256  data_time: 1.459  lr: 0.000226  max_mem: 2551M
[03/30 15:12:16 yolact.train]: eta: 16 days, 20:59:06  epoch: 0  iter: 80  B: 10.632  M: 2.320  C: 4.301  S: 0.827  T: 18.081  time: 1.636  data_time: 1.447  lr: 0.000244  max_mem: 2551M
[03/30 15:12:33 yolact.train]: eta: 16 days, 17:38:23  epoch: 0  iter: 90  B: 10.436  M: 2.236  C: 4.156  S: 0.763  T: 17.591  time: 3.349  data_time: 1.447  lr: 0.000262  max_mem: 2551M
Killed
```

## Warning

***I use the pretrained model `yolact_edge_54_800000.pth`, will this warning affect the training results?***

```
WARNING [03/30 15:09:46 yolact.model.load]: Some parameters in the checkpoint have a different shape in the current model, and are initialized as they should be: prediction_layers.0.conf_layer.weight, prediction_layers.0.conf_layer.bias, semantic_seg_conv.weight, semantic_seg_conv.bias
```
## Environment

```
CPU: i5-10400 6 Core 12 Threads
PC RAM: 16G
GPU: RTX 3060 - 12G RAM with CUDA : 11.0, cuDNN: 8.0.5 and Pytorch: 1.7.1
```

**Comment by winter2897** [comment]
Besides let me ask about the YOLACT EDGE training time on your `RTX 2080 Ti GPU`? With my `RTX 3060`,  logs giving me approximately 15 days of training  `eta: 15 days` ??

**Comment by haotian-liu** [comment]
It looks like an OOM (in physical RAM, not GPU RAM) issue. Try training with smaller image resolution / smaller backbone (e.g. R-50).

When I train with 4 RTX 2080Ti GPU, with per-GPU batch size of 8, it takes ~1 day to train.

**Comment by winter2897** [comment]
Thanks for your advice. I will try more options and will ask you later.
