### ISSUE TITLE
from yolact import Yolact doesn't work properly

### ISSUE THREAD

**Issue by mathmax12** [haotian-liu/yolact_edge#89]
Thanks for the amazing work and your code.
I can run the YOLACT on my machine. I also double-checked the installation env for the yolact_edge.
When I run `from yolact import Yolact` the script will stop by:
```
(yolact_edge) C:\Users\bigtree\Documents\prototype\segmentation\yolact_edge>python eval.py --trained_model=weights\yolact_edge_mobilenetv2_54_800000.pth --score_threshold=0.3 --top_k=100 --image=mom_kids_at_home.jpeg
b'\\\x00A\x00S\x00U\x00S\x00\\\x00A\x00r\x00m\x00o\x00u\x00r\x00y\x00D\x00e\x00v\x00i\x00c\x00e\x00\\\x00d\x00l\x00l\x00\\\x00 \x00w\x00a\x00s\x00 \x00u\x00n\x00e\x00x\x00p\x00e\x00c\x00t\x00e\x00d\x00 \x00a\x00t\x00 \x00t\x00h\x00i\x00s\x00 \x00t\x00i\x00m\x00e\x00.\x00\r\x00\n\x00'
Traceback (most recent call last):
  File "C:\Users\bigtree\.conda\envs\yolact_edge\lib\distutils\_msvccompiler.py", line 124, in _get_vc_env
    stderr=subprocess.STDOUT,
  File "C:\Users\bigtree\.conda\envs\yolact_edge\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "C:\Users\bigtree\.conda\envs\yolact_edge\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'cmd /u /c "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64 && set' returned non-zero exit status 255.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\bigtree\.conda\envs\yolact_edge\lib\site-packages\pyximport\pyximport.py", line 215, in load_module
    inplace=build_inplace, language_level=language_level)
  File "C:\Users\bigtree\.conda\envs\yolact_edge\lib\site-packages\pyximport\pyximport.py", line 191, in build_module
    reload_support=pyxargs.reload_support)
  File "C:\Users\bigtree\.conda\envs\yolact_edge\lib\site-packages\pyximport\pyxbuild.py", line 102, in pyx_to_dll
    dist.run_commands()
  File "C:\Users\bigtree\.conda\envs\yolact_edge\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\bigtree\.conda\envs\yolact_edge\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\bigtree\.conda\envs\yolact_edge\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Users\bigtree\.conda\envs\yolact_edge\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\Users\bigtree\.conda\envs\yolact_edge\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "C:\Users\bigtree\.conda\envs\yolact_edge\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\bigtree\.conda\envs\yolact_edge\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\bigtree\.conda\envs\yolact_edge\lib\distutils\command\build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "C:\Users\bigtree\.conda\envs\yolact_edge\lib\distutils\_msvccompiler.py", line 318, in compile
    self.initialize()
  File "C:\Users\bigtree\.conda\envs\yolact_edge\lib\distutils\_msvccompiler.py", line 215, in initialize
    vc_env = _get_vc_env(plat_spec)
  File "C:\Users\bigtree\.conda\envs\yolact_edge\lib\distutils\_msvccompiler.py", line 129, in _get_vc_env
    .format(exc.cmd))
distutils.errors.DistutilsPlatformError: Error executing cmd /u /c "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64 && set

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "eval.py", line 2, in <module>
    from yolact import Yolact
  File "C:\Users\bigtree\Documents\prototype\segmentation\yolact_edge\yolact.py", line 13, in <module>
    from layers import Detect
  File "C:\Users\bigtree\Documents\prototype\segmentation\yolact_edge\layers\__init__.py", line 1, in <module>
    from .functions import *
  File "C:\Users\bigtree\Documents\prototype\segmentation\yolact_edge\layers\functions\__init__.py", line 1, in <module>
    from .detection import Detect
  File "C:\Users\bigtree\Documents\prototype\segmentation\yolact_edge\layers\functions\detection.py", line 12, in <module>
    from utils.cython_nms import nms as cnms
  File "C:\Users\bigtree\.conda\envs\yolact_edge\lib\site-packages\pyximport\pyximport.py", line 462, in load_module
    language_level=self.language_level)
  File "C:\Users\bigtree\.conda\envs\yolact_edge\lib\site-packages\pyximport\pyximport.py", line 231, in load_module
    raise exc.with_traceback(tb)
  File "C:\Users\bigtree\.conda\envs\yolact_edge\lib\site-packages\pyximport\pyximport.py", line 215, in load_module
    inplace=build_inplace, language_level=language_level)
  File "C:\Users\bigtree\.conda\envs\yolact_edge\lib\site-packages\pyximport\pyximport.py", line 191, in build_module
    reload_support=pyxargs.reload_support)
  File "C:\Users\bigtree\.conda\envs\yolact_edge\lib\site-packages\pyximport\pyxbuild.py", line 102, in pyx_to_dll
    dist.run_commands()
  File "C:\Users\bigtree\.conda\envs\yolact_edge\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\bigtree\.conda\envs\yolact_edge\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\bigtree\.conda\envs\yolact_edge\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Users\bigtree\.conda\envs\yolact_edge\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\Users\bigtree\.conda\envs\yolact_edge\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "C:\Users\bigtree\.conda\envs\yolact_edge\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\bigtree\.conda\envs\yolact_edge\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\bigtree\.conda\envs\yolact_edge\lib\distutils\command\build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "C:\Users\bigtree\.conda\envs\yolact_edge\lib\distutils\_msvccompiler.py", line 318, in compile
    self.initialize()
  File "C:\Users\bigtree\.conda\envs\yolact_edge\lib\distutils\_msvccompiler.py", line 215, in initialize
    vc_env = _get_vc_env(plat_spec)
  File "C:\Users\bigtree\.conda\envs\yolact_edge\lib\distutils\_msvccompiler.py", line 129, in _get_vc_env
    .format(exc.cmd))
ImportError: Building module utils.cython_nms failed: ['distutils.errors.DistutilsPlatformError: Error executing cmd /u /c "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Auxiliary\\Build\\vcvarsall.bat" x86_amd64 && set\n']
```

Any suggestions?

**Comment by haotian-liu** [comment]
It could be due to the compatibility of distributed training package on Windows. You could verify by seeing if evaluation (which does not need distributed training) works fine on your machine.

**Comment by mathmax12** [comment]
It turns out that the conda env doesn't set up well.
I reinstall the CUDA and also the conda env. It works now.
Thanks.
